### ISSUE TITLE
Python script that imports pyVmomi and compiled into executable via pyInstaller or cx-freeze fails

### ISSUE THREAD

**Issue by bticc** [vmware/pyvmomi#1003]
### Describe the bug

I have a python app that automates the installation of n-tier application on multiple Windows virtual machines. The app uses pyVmomi to create snapshots of each VM prior to installation and remove those snapshots after the installation is validated. This works as expected when run as a python script in my development environment. The production environment does not have python installed and my intent is to compile the app into an executable using pyInstaller. If I exclude the module that uses pyVmomi when compiling the executable, the application works as expected without any VMWare snapshot functionality. When I compile the script into an executable and include the module using pyVmomi, the script compiles into an executable without errors, but when I try to run the executable it fails with the following error(s):

Traceback (most recent call last):
  File "pyVmomi\VmomiSupport.py", line 1781, in GetVmodlType
  File "pyVmomi\VmomiSupport.py", line 1167, in GetWsdlType
KeyError: 'None None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pdmain.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pdinstall.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "vmware.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pyVmomi\__init__.py", line 58, in <module>
  File "pyVmomi\VmomiSupport.py", line 1783, in GetVmodlType
KeyError: 'vmodl.DynamicData'
[12092] Failed to execute script 'pdmain' due to unhandled exception!

### Reproduction steps

1. Run pip install PyInstaller pyVmomi cx-freeze
2. Create python script, vmtest.py containing one line: print("Hello World")
3a. Compile script via: python -m PyInstaller vmtest.py
3b. COmpile script via: cxfreeze -c vmtest.py --target-dir dist
4a. Run dist\vmtest\vmtest.exe - prints Hello World in console as expected
4b. Run dist\vmtest.py - prints Hello World in console as expected
5. Now edit vmtest.py and add import pyVmomi above the print statement
6a. Compile script via: python -m PyInstaller vmtest.py
6b. COmpile script via: cxfreeze -c vmtest.py --target-dir dist
7a. Run dist\vmtest\vmtest.exe - fails with:
...PS C:\Users\username\Projects\test> dist\vmtest\vmtest
Traceback (most recent call last):
  File "pyVmomi\VmomiSupport.py", line 1781, in GetVmodlType
  File "pyVmomi\VmomiSupport.py", line 1167, in GetWsdlType
KeyError: 'None None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vmtest.py", line 1, in <module>
    import pyVmomi
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pyVmomi\__init__.py", line 58, in <module>
  File "pyVmomi\VmomiSupport.py", line 1783, in GetVmodlType
KeyError: 'vmodl.DynamicData'
[9288] Failed to execute script 'vmtest' due to unhandled exception!

7b. Run dist\vmtest.py faills with error:
PS C:\Users\username\Projects\test> dist\vmtest
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\pyVmomi\VmomiSupport.py", line 1781, in GetVmodlType
    typ = GetWsdlType(ns, wsdlName)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyVmomi\VmomiSupport.py", line 1167, in GetWsdlType
    raise KeyError("{0} {1}".format(ns, name))
KeyError: 'None None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 139, in run
    module_init.run(name + "__main__")
  File "C:\Program Files\Python311\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vmtest.py", line 1, in <module>
    import pyVmomi
  File "C:\Program Files\Python311\Lib\site-packages\pyVmomi\__init__.py", line 58, in <module>
    VmomiSupport.GetVmodlType("vmodl.DynamicData")
  File "C:\Program Files\Python311\Lib\site-packages\pyVmomi\VmomiSupport.py", line 1783, in GetVmodlType
    raise KeyError(name)
KeyError: 'vmodl.DynamicData'

### Expected behavior

Hello World should be displayed in the console window in both instances

### Additional context

Since the same error occurs whether compiling the python script to executable using either PyInstaller or cx-freeze, I have posted the issue here.

**Comment by bticc** [comment]
I have solved this on my own. Using the --collect-all=pyVmomi switch with PyInstaller allows the script to compile to an executable and run without errors
