### ISSUE TITLE
pyvmomi KeyError ContentLibrary , while fetching Events from vcenter 

### ISSUE THREAD

**Issue by navalkp** [vmware/pyvmomi#1016]
### Describe the bug

Gettting following exception on 
vCenter
Version:	7.0.3
Build:	20845200

python modules:
pyvim          3.0.3
pyvmomi        8.0.0.1.2

Traceback (most recent call last):
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 734, in LookupWsdlType
    return GetWsdlType(ns, name)
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 1182, in GetWsdlType
    typ = _LoadVmodlType(_wsdlDefMap[(ns, name)][0])
KeyError: ('urn:vim25', 'ContentLibrary')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "new_events.py", line 38, in <module>
    events_in_page = event_collector.ReadNextEvents(page_size)
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 598, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 388, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1551, in InvokeMethod
    obj = SoapResponseDeserializer(outerStub).Deserialize(
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 950, in Deserialize
    self.parser.ParseFile(response)
  File "../Modules/pyexpat.c", line 407, in StartElement
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 808, in StartElementHandler
    self.stack.append(self.LookupWsdlType(ns, name))
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 746, in LookupWsdlType
    return GuessWsdlType(name)
  File "/home/naval/play/vmware_tests/.venv/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 1211, in GuessWsdlType
    raise KeyError(name)
KeyError: 'ContentLibrary'

### Reproduction steps

Running following code snippet:

```
from datetime import datetime, timedelta
import ssl
from pyVim.connect import SmartConnect
from pyVmomi import vim

ssl._create_default_https_context = ssl._create_unverified_context

time_filter = vim.event.EventFilterSpec.ByTime()
now = datetime.now()
time_filter.beginTime = now - timedelta(hours=10000)
time_filter.endTime = now
event_type_list = []
filter_spec = vim.event.EventFilterSpec(eventTypeId=event_type_list, time=time_filter)

si = SmartConnect(
    host=<HOST_IP>,
    pwd=<PASSWORD,
    user=<USER>
)
eventManager = si.content.eventManager
event_collector = eventManager.CreateCollectorForEvents(filter_spec)
page_size = 1000 # The default and also the max event number per page till vSphere v6.5, you can change it to a smaller value by SetCollectorPageSize().
events = []

while True:
    events_in_page = event_collector.ReadNextEvents(page_size)
    num_event_in_page = len(events_in_page)
    if num_event_in_page == 0:
      break
    events.extend(events_in_page) # or do other things on the collected events

print(
    "Got totally {} events in the given time range from {} to {}.".format(
        len(events), time_filter.beginTime, time_filter.endTime
    )
  
)

print(events)

vm_info = {}
for event in events:
    if isinstance(event, vim.event.VmEvent):
        vm = event.vm
        if vm not in vm_info:
            # Initialize the VM info dictionary
            vm_info[vm] = {'created_by': None, 'last_modified_by': None}
        if isinstance(event, vim.event.VmCreatedEvent):
            vm_info[vm]['created_by'] = event.userName
        elif isinstance(event, vim.event.VmDeployedEvent):
            vm_info[vm]['created_by'] = event.userName
        elif isinstance(event, vim.event.VmReconfiguredEvent):
            vm_info[vm]['last_modified_by'] = event.userName
        elif isinstance(event, vim.event.VmRenamedEvent):
            vm_info[vm]['last_modified_by'] = event.userName
print(vm_info)
```

### Expected behavior

Should print event details for vmcreated events etc.

**Comment by DanielDraganov** [comment]
Hi Naval,
Thanks for reporting this one. It's not an issue of the pyVmomi client but rather of the server response from the underlying service.
It should detect that this isn't a known type for the client and omit it from the results.
The client could upcast unknown types but this would be rather unusable info.
Your issue is passed to our internal bug tracking and will be handled accordingly.
