### ISSUE TITLE
Release 8.0.3.0.0 can not be installed

### ISSUE THREAD

**Issue by wouterdb** [vmware/pyvmomi#1079]
### Describe the bug

When installing pyvmomi the follow happens

```
pip install pyvmomi      
Looking in indexes: https://artifacts.internal.inmanta.com/inmanta/dev
Collecting pyvmomi
  Using cached https://artifacts.internal.inmanta.com/root/pypi/%2Bf/326/7d8fd10d04d5c/pyvmomi-8.0.3.0.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/home/wouter/.virtualenvs/tmp-77a0c3e6b5b82f/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/wouter/.virtualenvs/tmp-77a0c3e6b5b82f/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/wouter/.virtualenvs/tmp-77a0c3e6b5b82f/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wdu5y0s0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wdu5y0s0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-wdu5y0s0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-wdu5y0s0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
        File "/tmp/pip-install-o7h1mzhz/pyvmomi_70a1984deb224ccd911f107f6f5ccd56/pyVmomi/__init__.py", line 49, in <module>
          from . import VmomiSupport  # noqa: E402
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-o7h1mzhz/pyvmomi_70a1984deb224ccd911f107f6f5ccd56/pyVmomi/VmomiSupport.py", line 12, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.


```

### Reproduction steps

```
pip install pyvmomi
```

### Expected behavior

For it to install

### Additional context

the setup.py importing the package itself breaks it 

I suspect this line https://github.com/vmware/pyvmomi/blame/f544b14b22cac8383de16e75887447e80b097391/setup.py#L21

**Comment by tsugliani** [comment]
I have the same issue.

**Comment by jinjamator** [comment]
Same here

**Comment by git4mandar** [comment]
We facing similar issues on our side. Pinning lib to an older version is working. But this needs to be fixed asap.
`pyVmomi==8.0.2`

**Comment by git4mandar** [comment]
I recommend reverting the current package until this issue is fixed.

**Comment by TheRealHaoLiu** [comment]
same

**Comment by DanielDraganov** [comment]
Hello to all. Apologies for the 
An emergency patch was just published - https://github.com/vmware/pyvmomi/releases/tag/v8.0.3.0.1
The fix is https://github.com/vmware/pyvmomi/commit/e4fd849
