### ISSUE TITLE
pyvmomi==8.0.3.0.1 errors with mypy

### ISSUE THREAD

**Issue by sodul** [vmware/pyvmomi#1080]
### Describe the bug

Run `mypy` on code using pyvmomi, mypy will throw an error:

```
AssertionError: Cannot find component 'ByTime' for 'pyVmomi.vim.event.EventFilterSpec.ByTime'
```

### Reproduction steps

`pip install pyvmomi==8.0.3.0.1 types-pyvmomi==8.0.0.6 mypy==1.10.1`

Call mypy on code using pyvmomi:
`mypy`

To fix:
`pip install pyvmomi==8.0.2.0.1`

### Expected behavior

No errors.

### Additional context

Relates to #862 and #1048.

**Comment by phagara** [comment]
another incorrect typing stub:
```
$ cat foo.py
from pyVmomi import vim
print(vim.TaskInfo.State.success)

$ python3 foo.py
success

$ mypy foo.py
foo.py:2: error: Module has no attribute "State"  [attr-defined]
    print(vim.TaskInfo.State.success)
          ^~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```

**Comment by IvarVirusiim** [comment]
Some more issues:
```
vm: vim.VirtualMachine
vm.runtime.powerState

error: RuntimeInfo? has no attribute "powerState"  
```


Something relating to `ManagedEntity`, because many objects get error for accessing name:
```
Datastore? has no attribute "name" 
Network? has no attribute "name" 
ManagedEntity? has no attribute "name" 
```

More examples:

```
TaskInfo? has no attribute "state" 
TaskInfo? has no attribute "result"
DatastoreBrowser? has no attribute "SearchDatastore_Task"  
VirtualDevice? has no attribute "connectable" 
VirtualDevice? has no attribute "uptCompatibilityEnabled" 
VirtualDevice? has no attribute "backing" 
VirtualHardware? has no attribute "device"
```


There seems to be an issue with the underlying generation issue. Those are some of the few examples.

**Comment by MajorDallas** [comment]
Here's another:

There are dozens of methods annotated with [`NoReturn`](https://docs.python.org/3/library/typing.html#typing.NoReturn) as their return type. `NoReturn` is meant to indicate that a function/method _does not return_, not that it returns nothing (for that, `None` is the correct annotation). Functions whose final statement is `raise SomeException()` or that call eg. `sys.exit()`--things that completely stop the execution of the program instead of returning--should use `NoReturn`. The effect is that any code after a call to eg. `View.Destroy()` or `ServiceSystem.Start()` will be incorrectly flagged by type checkers (not just mypy) as unreachable. 

Anything annotated with `-> NoReturn` should be changed to `-> None`. 

Just from a glance at the following line from `_typeinfo_vim.py`:

```python
CreateManagedType("vim.view.View", "View", "vmodl.ManagedObject", "vim.version.version2", None, [("destroy", "DestroyView", "vim.version.version2", (), (0, "void", "void"), "System.View", None)])
```

I will hazard a guess that `void` is the culprit. I don't know what vSphere's API is written in, but I've always assumed it's Java. So, I further guess that the meaning of `void` as "not having a return value" just doesn't translate well to Python, since all Python functions that don't raise an exception return _some_ value, even if it's an implicit `None`. Eg. this is correctly typed:

```python
def a_function() -> None:
    pass

# >>> result = a_function()
# >>> print(result)
# None
```

Oddly enough, I found this snippet in `VmomiSupport.py`:

```python
_wsdlTypeMap = {
    # Note: xsd has no void type. This is a hack from before. Can be removed?
    (XMLNS_XSD, 'void'):
    NoneType,
    ...
```

If this is what I think it is, it looks like the type stubs _should_ have `None` instead of `NoReturn`. Maybe the stubs just need to be regenerated?

**Comment by alexshpilkin** [comment]
@IvarVirusiim The issue you mention is due to the fact that a _lot_ more fields are now annotated as optional (including very basic ones like `vim.ServiceInstance.content`). If for example `VirtualDevice.connectable` is now an `Optional[VirtualDeviceConnectInfo]` and not just a `VirtualDeviceConnectInfo`, then you indeed will not be able to access its `name` until you prove to the typechecker that it is in fact a `VirtualDeviceConnectInfo` and not a `None`, as `None.name` is not a thing. Your https://github.com/vmware/pyvmomi/issues/1074 looks related.

I don’t know if all of that is correct in some sense, but I do know that it breaks my current code in a way that I’m not really willing to accomodate (dozens to a couple hundred new `assert ... is not None` statements for a thousand lines of code, which is an unacceptable amount of noise).

**Comment by MajorDallas** [comment]
And another, imo, major problem with type annotations:

`MethodFault` and its subclasses are not `Exception` types. This causes code like this to be flagged:

```python
try:
    WaitForTask(task)
except vim.fault.VimFault as error:  # "type[NoPermission]" is not a valid exception class
    logger.exception()
```

It doesn't help that `WaitForTask` is not typed at all, but this snippet:

```python
    info = task.info
    if state == "error":
        progressUpdater.Update("error: %s" % info.error)
        if raiseOnError:
            raise info.error
```

strongly suggests that `MethodFault` and its subclasses _are_ `Exception`s at runtime, even if the type stubs don't reflect that.

**Comment by alexshpilkin** [comment]
@MajorDallas No need to guess, they indeed are:

```python
>>> import pyVmomi
>>> issubclass(pyVmomi.vmodl.MethodFault, Exception)
True
>>> pyVmomi.vmodl.MethodFault.mro()
[<class 'pyVmomi.VmomiSupport.vmodl.MethodFault'>, <class 'pyVmomi.VmomiSupport.vmodl.DynamicData'>, <class 'pyVmomi.VmomiSupport.DataObject'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>]
```

**Comment by MajorDallas** [comment]
@alexshpilkin My earlier comment is focused on static typing, and type checkers cannot inspect an MRO on types that don't exist until runtime. The [type stub](https://github.com/vmware/pyvmomi/blob/master/pyVmomi/vmodl/MethodFault.pyi#L11) for `MethodFault`, for example, does not include `Exception` in its base classes, leaving type checkers in the dark about what this class actually is.

I'll add that even at runtime, fault objects can have their Exception-like nature erased:

```
...
  File "/usr/local/lib/python3.13/site-packages/pyVmomi/SoapAdapter.py", line 1472, in Invoke
Method
    raise obj  # pylint: disable-msg=E0702
    ^^^^^^^^^
pyVmomi.VmomiSupport.vmodl.fault.SystemError: (vmodl.fault.SystemError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Method vim.StorageResourceManager.recommendDatastores threw undeclared fault of typ
e vim.fault.NotFound',
   faultCause = (vim.fault.NotFound) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'The object or item referred to could not be found.',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) []
   },
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = 'Undeclared fault'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/celery/app/trace.py", line 499, in trace_task
    I, R, state, retval = on_error(task_request, exc)
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/celery/app/trace.py", line 407, in on_error
    R = I.handle_error_state(
        task, request, eager=eager, call_errbacks=call_errbacks,
    )
  File "/usr/local/lib/python3.13/site-packages/celery/app/trace.py", line 175, in handle_error_state
    return {
           ~
        RETRY: self.handle_retry,
        ~~~~~~~~~~~~~~~~~~~~~~~~~
        FAILURE: self.handle_failure,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    }[self.state](task, req,
    ~~~~~~~~~~~~~^^^^^^^^^^^
                  store_errors=store_errors,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
                  call_errbacks=call_errbacks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/celery/app/trace.py", line 225, in handle_failure
    if exc.__traceback__ is None:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DataObject' object has no attribute '__traceback__'
```

`DataObject` isn't an `Exception`, even at runtime, but it is in the MRO of `SystemError`. Something erased the `SystemError` type and the `__traceback__` along with it before Celery's error handlers could start processing it, so the fact `SystemError` is a subclass of `Exception` (at least at runtime, if not in the type stubs) became irrelvant.
