### ISSUE TITLE
Network interruption causes WaitForUpdatesEx blocking issue

### ISSUE THREAD

**Issue by austinnichols101** [vmware/pyvmomi#176]
The following code retrieves a list of host objects every 10 seconds.  For my test, I run this code on my laptop inside of a VMware Workstation Ubuntu VM.  This allows me to use VMware Workstation to simulate a break in network connectivity (adapter is up, but client is unable to communicate with vSphere).
1.  Allow the code to run for a few cycles (2-3 is enough).  
2.  Uncheck 'VM/Settings/Network Adapter' to simulate a break in network connectivity. 
3.  Wait 30 seconds - observe that 'Waiting for updates' does not show any updates or errors
4.  Re-enable 'VM/Settings/Network Adapter' to restore network connectivity
5.  Observe that 'Waiting for updates' does not show any further updates or errors.

``` python

    from pyVim.connect import SmartConnect
    import pyVmomi

    def test_loop(username, password, host, port):
        # Connect and collect instance info
        service_instance = SmartConnect(user=username, pwd=password, host=host, port=port)
        content = service_instance.RetrieveContent()

        # Create a container view
        container_view = content.viewManager.CreateContainerView(
            container=content.rootFolder,
            type=[pyVmomi.vim.HostSystem],
            recursive=True)

        # Create a traversal spec
        traversal_spec = pyVmomi.vim.PropertyCollector.TraversalSpec(
            name='traversal_spec',
            path='view',
            skip=False,
            type=pyVmomi.vim.view.ContainerView)

        # Create an object spec
        object_spec = pyVmomi.vim.PropertyCollector.ObjectSpec(
            obj=container_view,
            selectSet=[traversal_spec],
            skip=False)

        # Create a property specs for host events
        property_spec_host_events = pyVmomi.vim.PropertyCollector.PropertySpec(
            all=False,
            pathSet=["runtime.bootTime"],
            type=pyVmomi.vim.HostSystem)

        # Create a property filter spec
        property_filter_spec = pyVmomi.vim.PropertyCollector.FilterSpec(
            objectSet=[object_spec],
            propSet=[property_spec_host_events],
            reportMissingObjectsInResults=True)

        # Create the property filter
        content.propertyCollector.CreateFilter(
            spec=property_filter_spec,
            partialUpdates=True)

        # Set up the wait options
        max_wait = 10
        wait_options = pyVmomi.vim.PropertyCollector.WaitOptions(
            maxWaitSeconds=max_wait,
            maxObjectUpdates=None)

        # Initialize update version and start time
        update_version = None

        # Loop until exit flag has been set
        while True:

            print("Waiting for updates from (v {})...({} seconds)".format(
                update_version,
                wait_options.maxWaitSeconds))

            # Block until an update is received or timeout is received
            update_set = content.propertyCollector.WaitForUpdatesEx(
                version=update_version,
                options=wait_options)

            if update_set is None:
                print("Timeout/Requery")

                # Reset the update version number to force a full requery.
                update_version = None

            else:
                print("  Received Update (v{})".format(update_set.version))
                update_version = update_set.version

            print("")

    # Run the test.
    test_loop('root', 'password', 'localhost', 443)
```

**Comment by arkfps** [comment]
This is a classic [TCP half-open](https://en.wikipedia.org/wiki/TCP_half-open) problem. The `WaitForUpdatesEx` is most vulnerable to this issues because of its long running nature. The most simple and reliable fix is to enable `TCP Keepalive` on underlying socket using `setsockopt` with relevant options (POSIX) or `SIO_KEEPALIVE_VALS` (Windows API).

**Comment by hartsock** [comment]
Attn: @tianhao64

**Comment by kelvie-pstg** [comment]
Sorry to dig up a 4 year old bug, but we've also been running into this occasionally (on somewhat flaky networks), where we are blocked indefinitely on a property read, even though the WaitForUpdates fails (according to the viclient logs) after 15 minutes:

```
[viclient:SoapTran:W:20] 2019-05-14 15:30:52.673  Invoke 1096 Start WaitForUpdates on PropertyCollector:session<redacted>

<snip>

[viclient:SoapTran:W:20] 2019-05-14 15:45:52.686  Invoke 1096 Finish WaitForUpdates on PropertyCollector:session<redacted>
Suppressed: VirtualInfrastructure.Soap.MethodInvocationSoapImpl: The request failed because the remote server 'vcenter.lan' took too long to respond. (The command has timed out as the remote server is taking too long to respond.)
[viclient:Error   :W:20] 2019-05-14 15:45:52.686  ConnectionError occurred while executing WFU
VirtualInfrastructure.Exceptions.RequestTimedOut: The request failed because the remote server 'vcenter.lan' took too long to respond. (The command has timed out as the remote server is taking too long to respond.)
   at VirtualInfrastructure.Soap.SoapServiceWrapper.DoInvokeSync(ManagedObject mo, MethodName methodName, Object[] parameters, Int32 timeoutSecs)
   at VirtualInfrastructure.Soap.SoapTransport.VirtualInfrastructure.Transport.InvokeMethod(ManagedObject mo, MethodName methodName, Object[] pars)
   at VirtualInfrastructure.ManagedObject.InvokeMethod(MethodName methodName, Object[] pars)
   at Vmomi.Core.PropertyCollector.WaitForUpdates(String version)
   at VirtualInfrastructure.Updates.PollerDispatcherImpl.ExecuteSingleWFU()
   at VirtualInfrastructure.Updates.PollerDispatcherImpl.PollWaitForUpdates()
 System.Net.WebException: The command has timed out as the remote server is taking too long to respond.
```
The code hangs indefinitely (it's been like this for several days):

```
    mor_config = mor.config
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1347, in InvokeMethod
    obj = deserializer.Deserialize(fd, info.result)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 833, in Deserialize
    ParseData(self.parser, response)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 502, in ParseData
    parser.ParseFile(data)
  File "/usr/local/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/usr/local/lib/python3.6/http/client.py", line 583, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/local/lib/python3.6/http/client.py", line 628, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
```

Googling around, this seems to be a problem in the java client as well:

https://sourceforge.net/p/vijava/bugs/113/

**Comment by kelvie-pstg** [comment]
Strangely, this happens most often when grabbing a host's config.

**Comment by hartsock** [comment]
@kelvie-pstg I'm not working this project anymore so I can't advocate for it internally in VMware, @pgbidkar are you aware of this issue and can you advocate for it internally? Thanks.
