### ISSUE TITLE
SmartConnect Failing

### ISSUE THREAD

**Issue by zukeru** [vmware/pyvmomi#196]
So I wrote a program that connects to vCenter API using pyvmomi and when I try to run it on my production box I get the following error:

2014-12-03 21:07:00,453 CRITICAL Unexpected error: <type 'exceptions.IOError'>
2014-12-03 21:22:13,060 ERROR ApplicationError
Traceback (most recent call last):
  File "/opt/metering-home/code/PortalBackendController.py", line 193, in vm_command_center
    vcenter_connection = SmartConnect(host=hostname,user=username,pwd=password)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 575, in SmartConnect
    preferredApiVersions)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 518, in __FindSupportedVersion
    path)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 432, in __GetServiceVersionDescription
    with closing(urllib.urlopen(url)) as sock:
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 22] Invalid argument
2014-12-03 21:22:13,062 CRITICAL Unexpected error: <type 'exceptions.IOError'>

However, 
       I don't get an error when I run it on my development box. I pasted my code below, I'm not sure what the problem is it doesn't really explain it in the error well and it works on one box and not the other. The versions of the packages are the same as well.

```
#!/usr/bin/python
"""
SYNOPSIS

    PortalBackendController.py

DESCRIPTION

    Spawn multiple processes which control the VM Status and Commands page. Status_Worker reports the updated VM Statues to the database, and vm_commander executes commands saved in the database and returns the status to the database of the command.

EXAMPLES

    None.

EXIT STATUS

    Module will raise an exception on abnormal termination.

AUTHOR

    Grant Zukel

INITIAL VERSION

    03-Dec-14

COPYRIGHT

    This script is in owned and (C) 2013 by ENKI Corporation.  All rights are reserved.
    Use of this program without written permission is prohibited.    

VERSION HISTORY

    1.0   Initial version

"""
import atexit
import calendar
import cx_Oracle
from datetime import datetime
from metering import *
import os
import psycopg2
from pyVim.connect import SmartConnect, Disconnect
from pyVmomi import vim
import sys
import time
import pchelper
import requests

from multiprocessing import Process
from Crypto.Cipher import XOR
import base64

def encrypt(key, plaintext):
  cipher = XOR.new(key)
  return base64.b64encode(cipher.encrypt(plaintext))

def status_worker():
   vc_thread = {}
   uuid_dict = {}
   vm_dict = {}
   requests.packages.urllib3.disable_warnings()
   list_of_vc_connections = {}  
   try:
      config_values = metering_config('VMStatus',['logfile','daemon', 'pguser','pgpassword','pghost','pgport'])     # Get the configuration file options
      open_log(config_values['logfile'], logging.INFO)         # Open the Logfile
      semaphore('VMStatus', True)

      '''
      Become a daemon
      '''
      if config_values['daemon'].upper() == 'TRUE' or config_values['daemon'].upper() == 'YES':
     if os.fork():
        sys.exit()

      config_values_vc = metering_config('VSphereManager',['vcenter-ip','username','password','api-version'])
      for k in xrange(0, len(config_values_vc['username'])):   # Loop through each vcenter server
        password = config_values_vc['password'][k]
        hostname = config_values_vc['vcenter-ip'][k]
        username = config_values_vc['username'][k]
        vcenter_connection = SmartConnect(host=hostname,user=username,pwd=password)
        atexit.register(Disconnect, vcenter_connection)
        content = vcenter_connection.RetrieveContent()

        if not vcenter_connection:
           logging.error("Could not connect to vcenter-ip %s" % (str(hostname)))
           continue
        uuid_dict[config_values_vc['vcenter-ip'][k]] = content.about.instanceUuid
        list_of_vc_connections[config_values_vc['vcenter-ip'][k]] = vcenter_connection

      postgres = psycopg2.connect(database='metering', user=config_values['pguser'], password=config_values['pgpassword'],host=config_values['pghost'], port=config_values['pgport']) 
      pg_cursor = postgres.cursor()
      oracle,data_dict = db_init()    # Open the connection to the DB 
      oracle_cursor = oracle.cursor()

      while True:
        logging.info("Starting to get VM Power Status")
        t0_clock = time.clock()
        t0_time = time.time()
        pg_cursor.execute('SET SESSION TIMEZONE TO MST7MDT')
        postgres.commit()

        for vcenter in list_of_vc_connections:
           list_of_vc_connections[vcenter].CurrentTime()
           vm_properties = ["name","runtime.powerState", "summary.config.instanceUuid"]         
           root_folder = list_of_vc_connections[vcenter].content.rootFolder
           view = pchelper.get_container_view(list_of_vc_connections[vcenter], obj_type=[vim.VirtualMachine])
           vm_data = pchelper.collect_properties(list_of_vc_connections[vcenter], view_ref=view, obj_type=vim.VirtualMachine, path_set=vm_properties, include_mors=True)
           for virtual_machine in vm_data:
          vm_mor = str(virtual_machine['obj']).split(':')[1]
          vm_mor = vm_mor.replace("'","")
          power_state = virtual_machine['runtime.powerState']   
          vm_name = virtual_machine['name']
          vm_uuid = virtual_machine['summary.config.instanceUuid']
          oracle_cursor.execute('''select c.vm_id, a.customer_id from customers a, vm_groups b, vms c where a.customer_id = b.customer_id and b.vm_group_id = c.vm_group_id and c.vm_mor = '%s' ''' % vm_mor)
          returned_row = oracle_cursor.fetchone()

          if returned_row:
             pg_cursor.execute('''select * from portal_command_center where vm_id = %s ''' % returned_row[0])
             check_exist = pg_cursor.fetchone()
             if not check_exist:
            pg_cursor.execute('''insert into portal_command_center(vm_id, vm_uuid, power_state, vm_name, customer_id) 
                           values(%s,'%s', '%s', '%s', %s)''' % (returned_row[0],vm_uuid, power_state, vm_name, returned_row[1]))
             else:
            pg_cursor.execute('''update portal_command_center set power_state='%s' where vm_id = %s ''' % (power_state, returned_row[0]))
        postgres.commit()                             
        runtime = time.time() - t0_time 
        logging.info("Commplete Runtime %s" %(runtime/60))
   except ApplicationError:
      logging.exception('ApplicationError')
      semaphore('VMStatus', False)
      try:        # Close the db is it is open (db is defined)
     oracle.close()
     postgres.close()
      except:
     pass
      sys.exit(1)

   except Abort:  # Exit without clearing the semaphore
      logging.exception('ApplicationError')
      try:        # Close the db is it is open (db is defined)
     oracle.close()
     postgres.close()
      except:
     pass
      sys.exit(1)

   except SystemExit:
      raise

   except:
      logging.exception('ApplicationError')
      semaphore('VMStatus', False)
      logging.critical('Unexpected error: %s' % sys.exc_info()[0])
      raise       # Raise the same exception to allow the caller to handle the exception as well

def vm_command_center():  
   def login_header(user, org, pw, api):
      credentials = '%s@%s:%s' % (user, org, pw)
      credentials = str.encode(credentials, 'UTF-8')
      encoded_credentials = base64.b64encode(credentials)
      encoded_credentials = encoded_credentials.decode('UTF-8')
      authorization_string = 'Basic %s' % encoded_credentials
      accept_string = 'application/*+xml;version=%s' % api
      return {'Authorization': authorization_string,
            'Accept': accept_string}
   vc_thread = {}
   uuid_dict = {}
   vm_dict = {}
   requests.packages.urllib3.disable_warnings()
   list_of_vc_connections = {}           
   api='5.5'
   header = login_header('Administrator', 'System', 'ENKIops123!', api)

   try:
      config_values = metering_config('VMCommander',['logfile','daemon', 'pguser','pgpassword','pghost','pgport','encryption-key'])     # Get the configuration file options
      open_log(config_values['logfile'], logging.INFO)         # Open the Logfile
      semaphore('VMCommander', True)
      secret_key = config_values['encryption-key']
      '''
      Become a daemon
      '''
      if config_values['daemon'].upper() == 'TRUE' or config_values['daemon'].upper() == 'YES':
     if os.fork():
        sys.exit()

      config_values_vc = metering_config('VSphereManager',['vcenter-ip','username','password','api-version'])
      for k in xrange(0, len(config_values_vc['username'])):   # Loop through each vcenter server
     password = config_values_vc['password'][k]
     hostname = config_values_vc['vcenter-ip'][k]
     username = config_values_vc['username'][k]
     vcenter_connection = SmartConnect(host=hostname,user=username,pwd=password)
     atexit.register(Disconnect, vcenter_connection)
     content = vcenter_connection.RetrieveContent()

     if not vcenter_connection:
        logging.error("Could not connect to vcenter-ip %s" % (str(hostname)))
        continue
     uuid_dict[config_values_vc['vcenter-ip'][k]] = content.about.instanceUuid
     list_of_vc_connections[config_values_vc['vcenter-ip'][k]] = vcenter_connection


      postgres = psycopg2.connect(database='metering', user=config_values['pguser'], password=config_values['pgpassword'],host=config_values['pghost'], port=config_values['pgport'])

      pg_cursor = postgres.cursor()
      command_cursor = postgres.cursor()
      check_command_cursor = postgres.cursor()
      update_cursor = postgres.cursor()

      oracle,data_dict = db_init()    # Open the connection to the DB 
      oracle_cursor = oracle.cursor()   

      while True:
     vcd = False
     command_dict = {}
     vcd_dict = {}
     for vcenter in list_of_vc_connections:
        list_of_vc_connections[vcenter].CurrentTime()

     command_cursor.execute('''select vm_id, vm_name, vm_uuid, customer_id, power_state, command_state, username, ip_address, command_issued_time, command_completed_time from portal_command_center where command_state != '' ''')

     for row in command_cursor:               
        vm_id=row[0]
        vm_name=row[1]
        vm_uuid=row[2]
        customer_id=row[3]
        power_state=row[4]
        command_state=row[5]
        username=row[6]
        ip_address=row[7]
        command_issued_time=row[8]
        command_completed_time=row[9]
        logging.info("User %s, issued the following command %s, from ip_address %s, the current power state %s, the vm_name %s, the vm_id %s" % (str(username), str(command_state), str(ip_address), str(power_state), str(vm_name), str(vm_id)))

        ''' Generate token from the command sender and match to the token generated when the user logged in '''

        token_to_generate = username + ip_address
        token=encrypt(secret_key, token_to_generate) 
        pg_cursor.execute('''select customer_id, token from command_token where token = '%s' ''' % token)
        row = pg_cursor.fetchone()

        '''
        If the row exist then the token matches and we can proceed to building the command_dict which is controls the execution and flow of commands.
        '''

        if row:
           if vm_id not in command_dict:
          command_dict[vm_id] = {'vm_id':vm_id, 'vm_uuid':vm_uuid, 'vm_name':vm_name, 'customer_id':customer_id,'power_state':power_state, 'command':command_state, 'username':username, 'ip_address':ip_address, 'command_issued_time': command_issued_time, 'command_completed_time':command_completed_time }

        for command in command_dict: 
           ''' This is where we pass the completetion to the website and clear the command state '''
           if command_dict[command]['command'] == 'success':
          update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('', command_dict[command]['vm_id']))
          postgres.commit()  

           if command_dict[command]['command'] == 'already in state':
          update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('', command_dict[command]['vm_id']))
          postgres.commit()  

           for vcenter in list_of_vc_connections:
          #call the current time to keep the connection alive.
          list_of_vc_connections[vcenter].CurrentTime()
          vm_uuid = command_dict[command]['vm_uuid']
          search_index = list_of_vc_connections[vcenter].content.searchIndex
          vm = search_index.FindByUuid(None, vm_uuid, True, True)
          command_exec = command_dict[command]['command']
          vcenter_uuid = uuid_dict[vcenter]
          vm_mor = vm._moId

          for option in vm.config.extraConfig:
             if option.key == 'cloud.uuid':
            vcd = True
            vm_vcd_uuid = vm.config.name.split('(')[1]
            vm_vcd_uuid = vm_vcd_uuid.replace(')', '')
          if vcd:
            url = 'https://vcloud.enki.co'
            r=requests.post(url + '/api/sessions', headers = header)
            new_headers = {r.headers._store['x-vcloud-authorization'][0]: r.headers._store['x-vcloud-authorization'][1], 'Accept': 'application/*+xml;version=%s' % api}                           

            if command_exec == 'powerOn':
               vcd = False 
               power_on_url = 'https://vcloud.enki.co/api/vApp/vm-' + vm_vcd_uuid + '/power/action/powerOn'
               if vm.runtime.powerState != 'poweredOn':
                  r=requests.post(power_on_url, headers = new_headers)
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
                  postgres.commit()
                  response = str(r)
                  if '202' in response:
                 update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('success', command_dict[command]['vm_id'])) 
                 postgres.commit()  
                 command_dict[command]['command'] = 'success' 
                 time.sleep(5) 
                  else:
                 update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
                 postgres.commit()
                 time.sleep(5)
                 '''this will display an error message for 5 seconds until it loops through and re-attemps the command. '''
               else:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('already in state', command_dict[command]['vm_id'])) 
                  postgres.commit()
                  time.sleep(5)                                              

            if command_exec == 'powerOff':
               vcd = False
               power_off_url = 'https://vcloud.enki.co/api/vApp/vm-' + vm_vcd_uuid + '/power/action/powerOff'
               if vm.runtime.powerState != 'poweredOff':
                  r=requests.post(power_off_url, headers = new_headers)
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
                  postgres.commit()
                  response = str(r)
                  if '202' in response:
                 update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('success', command_dict[command]['vm_id'])) 
                 postgres.commit()  
                 command_dict[command]['command'] = 'success' 
                 time.sleep(5) 
                  else:
                 update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
                 postgres.commit()
                 time.sleep(5)
                 '''this will display an error message for 5 seconds until it loops through and re-attemps the command. '''
               else:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('already in state', command_dict[command]['vm_id'])) 
                  postgres.commit()
                  time.sleep(5)                                            

            if command_exec == 'Reset':
               vcd = False
               reset_url = 'https://vcloud.enki.co/api/vApp/vm-' + vm_vcd_uuid + '/power/action/reboot'
               r=requests.post(reset_url, headers = new_headers)                           
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
               postgres.commit()
               response = str(r)
               if '202' in response:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('success', command_dict[command]['vm_id'])) 
                  postgres.commit()  
                  command_dict[command]['command'] = 'success' 
                  time.sleep(5) 
               else:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
                  postgres.commit()
                  time.sleep(5)
                  '''this will display an error message for 5 seconds until it loops through and re-attemps the command. '''

          else:                       
             if command_exec == 'powerOn': 
            if vm.runtime.powerState != 'poweredOn':
               task = vm.PowerOn()
               '''This while statement puts the program in a loop while the task is executing. '''
               while task.info.state not in [vim.TaskInfo.State.success,vim.TaskInfo.State.error]:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
                  postgres.commit()
               '''if the task was a success insert success into the database. If it is not a success it will remain in the dictonary and get attempted again on the next go thru'''
               if task.info.state == 'success':
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % (task.info.state, command_dict[command]['vm_id'])) 
                  postgres.commit()
                  command_dict[command]['command'] = 'success'
                  time.sleep(5)
                  '''this gives the portal the time to display completed, it knows based on success being in the database. 
                  Thus we sleep for 5 seconds. Thus, on the portal the message associated with success will be displayed for five seconds.
                  Then on the next run success will be wipped from the command state in the db and it will disappear off of the portal '''
               else:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
                  postgres.commit()
                  time.sleep(5)
                  '''this will display an error message for 5 seconds until it loops through and re-attemps the command. '''  
            else:
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('already in state', command_dict[command]['vm_id'])) 
               postgres.commit()
               time.sleep(5)
               #this will display an error message for 5 seconds until it loops through and re-attemps the command.                                             

             if command_exec == 'powerOff':
            if vm.runtime.powerState != 'poweredOff':
               task = vm.PowerOff()
               while task.info.state not in [vim.TaskInfo.State.success,vim.TaskInfo.State.error]:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
                  postgres.commit()
               if task.info.state == 'success':
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % (task.info.state, command_dict[command]['vm_id'])) 
                  postgres.commit()  
                  command_dict[command]['command'] = 'success' 
                  time.sleep(5) 
               else:
                  update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
                  postgres.commit()
                  time.sleep(5)
                  '''this will display an error message for 5 seconds until it loops through and re-attemps the command. '''
            else:
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('already in state', command_dict[command]['vm_id'])) 
               postgres.commit()
               time.sleep(5)                                            

             if command_exec == 'Reset':
            task = vm.ResetVM_Task()

            while task.info.state not in [vim.TaskInfo.State.success,vim.TaskInfo.State.error]:
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('in process', command_dict[command]['vm_id']))
               postgres.commit()
            if task.info.state == 'success':
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % (task.info.state, command_dict[command]['vm_id'])) 
               postgres.commit()  
               command_dict[command]['command'] = 'success'
               time.sleep(5)
            else:
               update_cursor.execute('''update portal_command_center set command_state='%s' where vm_id = %s ''' % ('error', command_dict[command]['vm_id'])) 
               postgres.commit()
               time.sleep(5)


   except ApplicationError:
      logging.exception('ApplicationError')
      semaphore('VMCommander', False)
      try:        # Close the db is it is open (db is defined)
     oracle.close()
     postgres.close()
      except:
     pass
      sys.exit(1)

   except Abort:  # Exit without clearing the semaphore
      logging.exception('ApplicationError')
      try:        # Close the db is it is open (db is defined)
     oracle.close()
     postgres.close()
      except:
     pass
      sys.exit(1)

   except SystemExit:
      raise

   except:
      logging.exception('ApplicationError')
      semaphore('VMCommander', False)
      logging.critical('Unexpected error: %s' % sys.exc_info()[0])
      raise       # Raise the same exception to allow the caller to handle the exception as well


#start the worker processes.
status_worker = Process(target=status_worker, args=())
command_worker = Process(target=vm_command_center, args=())
status_worker.start()
command_worker.start()

while True:

   if status_worker.is_alive():
      pass
   else:
      semaphore('VMCommander', False)
      semaphore('VMStatus', False)
      sys.exit(1)

   if command_worker.is_alive():
      pass
   else:
      semaphore('VMCommander', False)
      semaphore('VMStatus', False)
      sys.exit(1)
   time.sleep(1)
```

**Comment by einarc** [comment]
Here's the answer:
https://github.com/vmware/pyvmomi/issues/513
