### ISSUE TITLE
no support for proxy for 5.1

### ISSUE THREAD

**Issue by r1k0** [vmware/pyvmomi#198]
Hi guys,
In our company, we're about to migrate some code from pysphere to pyvmomi.
I'm working with https://github.com/vmware/pyvmomi/releases/tag/v5.1.0.
We have an internal proxy where all connections pass through and that caused an issue.

```
rik /tmp $ python2
Python 2.7.8 (default, Sep 24 2014, 18:26:21) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyVim.connect as connect
>>> s = connect.SmartConnect(host='xxxxxx',user='id8xxxx',pwd='xxxxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pyVim/connect.py", line 580, in SmartConnect
    raise Exception("%s:%s is not a VIM server" % (host, port))
Exception: xxxxxxxxx:443 is not a VIM server
>>> 
```

After having changed __GetServiceVersionDescription() in pyVim/connect.py from:

``` python
428    tree = ElementTree()
429 
430    url = "%s://%s:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
431    try:
432       with closing(urllib.urlopen(url)) as sock:
433          if sock.getcode() == 200:
434             tree.parse(sock)
435             return tree
436    except ExpatError:
437       pass
438 
439    url = "%s://%s:%s/%s/vimService.wsdl" % (protocol, server, port, path)
440    try:
441       with closing(urllib.urlopen(url)) as sock:
442          if sock.getcode() == 200:
443             tree.parse(sock)
444             return tree
445    except ExpatError:
446       pass
447 
448    return None
```

to:

``` python
428    tree = ElementTree()
429 
430    uprox='xxxxx'
431    pprox='xxxxxxx'
432    proxy="http://%s:%s@XXX.X.X.X:8080" % (uprox, pprox)
433    
434    url = "%s://%s:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
435 #   with closing(urllib.urlopen(url)) as sock:
436    with closing(urllib.urlopen(url, proxies = {'http': proxy})) as sock:
437      if sock.getcode() == 200:
438       tree.parse(sock) 
439       print 'tree1'
440       print tree
441       return tree
442       
443    
444    url = "%s://%s:%s/%s/vimService.wsdl" % (protocol, server, port, path)
445 #   with closing(urllib.urlopen(url)) as sock:
446    with closing(urllib.urlopen(url, proxies = {'http': proxy})) as sock:
447       if sock.getcode() == 200:
448          tree.parse(sock)
449          print 'tree2'
450          print tree
451          return tree
452    
453    return None
```

I get:

```
rik ~ $ python2
Python 2.7.8 (default, Sep 24 2014, 18:26:21) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyVim.connect import SmartConnect, Disconnect
>>> s=SmartConnect(host='xxxxx.be',user='xxxxx',pwd='xxxxxx')
preferredApiVersions
['vim.version.version9', 'vim.version.version8', 'vim.version.version7', 'vim.version.version6', 'vim.version.version5', 'vim.version.version4', 'vmodl.query.version.version4', 'vim.version.version3', 'vmodl.query.version.version3', 'vim.version.version2', 'vmodl.version.version2', 'vmodl.query.version.version2', 'vim.version.version1', 'vmodl.version.version1', 'vmodl.query.version.version1', 'vmodl.version.version0']
tree1
<xml.etree.ElementTree.ElementTree object at 0x7f73f8268b10>
serviceVersionDescription
<xml.etree.ElementTree.ElementTree object at 0x7f73f8268b10>
vim.version.version8
>>> 
```

which looks much nicer.

Questions: 
- Are you guys still supporting 5.1?
- Is this a known issue on 5.5?

Thanks for your support and for this great software, helps us a lot doing our work.

**Comment by wyaeld** [comment]
@tianhao64 after just spending a couple of hours down the rabbit hole on this, can confirm in also affects pyvmomi 5.5

Is it intended to be fixed?

**Comment by r1k0** [comment]
@wyaeld 
I wish I hadn't wasted so much time on this project at work given the support. P1 for a year and half almost, that's good priority management obviously.

**Comment by wyaeld** [comment]
I'll willing to give them the benefit of the doubt, I did have a conversation with @hartsock that seemed encouraging

**Comment by C01DER** [comment]
Python 2.7.11 still hit on this issue. Any update  here?
Python 2.7.7 hit on ssl verification issue.  

I'm running hello_world_vcenter.py

**Comment by jpeanut** [comment]
another year passed .... Has this issue been solved ?  I think I got the same problem ... OMG

**Comment by tianhao64** [comment]
The SmartConnect doesn't accept proxy parameter yet. However, the lower level SoapStubAdapter supports it. Would you like to give that a try before we add the support to SmartConnect?

**Comment by blacksponge** [comment]
@tianhao64  Hi, I tested that and as far as I can see SoapStubAdapter seems to be working but it is now SSLTunnelConnection that cause a problem as explained in #567
