### ISSUE TITLE
Autostart Manager Reconfiguration failed

### ISSUE THREAD

**Issue by kellerkind** [vmware/pyvmomi#220]
When configuring Autostart Options for a virtual machine the virtual machine is not found.

def set_host_autostart(host, vm):

    defaults = { 'start_delay': 120, 'stop_delay': 65535, 'start_action': 'powerOn', 'stop_action': 'GuestShutdown' }
    asm = host.configManager.autoStartManager

    asm_spec = vim.host.AutoStartManager.Config()
    asm_spec.defaults = vim.host.AutoStartManager.SystemDefaults(enabled=True, startDelay=defaults['start_delay'],
                                                                               stopDelay=defaults['stop_delay'],
                                                                               stopAction=defaults['stop_action'])

    power_info = vim.host.AutoStartManager.AutoPowerInfo(key=vm,
                                                         waitForHeartbeat=vim.host.AutoStartManager.AutoPowerInfo.WaitHeartbeatSetting.systemDefault,
                                                                startOrder=1,
                                                                startDelay=defaults['start_delay'],
                                                                stopDelay=defaults['stop_delay'],
                                                                startAction=defaults['start_action'],
                                                                stopAction=defaults['stop_action'])
    asm_spec.powerInfo = [power_info]

    print asm_spec

    asm.ReconfigureAutostart(asm_spec)

print asm_spec:

	(vim.host.AutoStartManager.Config) {
	   dynamicType = <unset>,
	   dynamicProperty = (vmodl.DynamicProperty) [],
	   defaults = (vim.host.AutoStartManager.SystemDefaults) {
		  dynamicType = <unset>,
		  dynamicProperty = (vmodl.DynamicProperty) [],
		  enabled = true,
		  startDelay = 120,
		  stopDelay = 65535,
		  waitForHeartbeat = <unset>,
		  stopAction = 'GuestShutdown'
	   },
	   powerInfo = (vim.host.AutoStartManager.AutoPowerInfo) [
		  (vim.host.AutoStartManager.AutoPowerInfo) {
			 dynamicType = <unset>,
			 dynamicProperty = (vmodl.DynamicProperty) [],
			 key = 'vim.VirtualMachine:vm-182',
			 startOrder = 1,
			 startDelay = 120,
			 waitForHeartbeat = 'systemDefault',
			 startAction = 'powerOn',
			 stopDelay = 65535,
			 stopAction = 'GuestShutdown'
		  }
	   ]
	}

Raised Error:

	Traceback (most recent call last):
	  File "./create_vm.py", line 346, in <module>
		main()
	  File "./create_vm.py", line 341, in main
		set_host_autostart(host, vm)
	  File "./create_vm.py", line 176, in set_host_autostart
		asm.ReconfigureAutostart(asm_spec)
	  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 566, in <lambda>
	  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
	  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1300, in InvokeMethod
	pyVmomi.VmomiSupport.ManagedObjectNotFound: (vmodl.fault.ManagedObjectNotFound) {
	   dynamicType = <unset>,
	   dynamicProperty = (vmodl.DynamicProperty) [],
	   msg = 'The object has already been deleted or has not been completely created',
	   faultCause = <unset>,
	   faultMessage = (vmodl.LocalizableMessage) [],
	   obj = 'vim.VirtualMachine:vm-2'
	}

**Comment by suederat** [comment]
It could be you need to pass in a str(uuid) rather than an object. I saw this problem in template cloning when I passed in a datastore object. I replaced the parameter for clonespec.datastore with the uuid of the target datastore and the problem stopped happening. I did not change the other parameters from object to uuid for resource-pool etc, so it may require trial and error!

**Comment by mcandre** [comment]
> It could be you need to pass in a str(uuid) rather than an object.

If so, then could we validate earlier and more aggressively?
