### ISSUE TITLE
I have a problem with urllib3

### ISSUE THREAD

**Issue by aleks81R** [vmware/pyvmomi#225]
Python 3.4 64, Windows Server 2012 R2.

When i Run the command:
C:\Python34\Scripts\pyvmomi\sample>C:\Python34\python.exe getallvms.py -s 'host' -u 'user' -p 'password'

The program gives an error:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 204, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.
py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py",
line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\packages\six.py"
, line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 204, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.
py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', gaie
rror(11001, 'getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getallvms.py", line 122, in <module>
    main()
  File "getallvms.py", line 102, in main
    port=int(args.port))
  File "C:\Python34\lib\site-packages\pyVim\connect.py", line 577, in SmartConne
ct
    preferredApiVersions)
  File "C:\Python34\lib\site-packages\pyVim\connect.py", line 520, in __FindSupp
ortedVersion
    path)
  File "C:\Python34\lib\site-packages\pyVim\connect.py", line 435, in __GetServi
ceVersionDescription
    sock = requests.get(url, verify=False)
  File "C:\Python34\lib\site-packages\requests\api.py", line 65, in get
    return request('get', url, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 461, in reques
t
    resp = self.send(prep, *_send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(11001, 'ge
taddrinfo failed'))

C:\Python34\Scripts\pyvmomi\sample>

Can you help me?

**Comment by DanielDraganov** [comment]
Outdated
