### ISSUE TITLE
QueryEvents in EventsManager unsupported ? 

### ISSUE THREAD

**Issue by srimandaleeka** [vmware/pyvmomi#268]
Hello Team members !

I want to detect Events  for a particular VM and host , so my python code does the following :  
Once I have the VM MOREF , I do the following: 
# Step1 : Create a EventFilterSpecByEntity

```
        efespec = vim.event.EventFilterSpec.ByEntity() 
        efespec.entity = vm 
        efespec.recursion = vim.event.EventFilterSpec.RecursionOption.all 
```
# Step2 :Event Spec Filter

```
        efspec = vim.event.EventFilterSpec() 
        efspec.entity = efespec 
```
# Step3: QueryEvents

```
       events = si.content.eventManager.QueryEvents(efspec) 
```

Any ideas if QueryEvents in EventsManager is implemented and supported to start off with ? 

I get the following errors : 
 print si.content.eventManager.QueryEvents(efspec) 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "/build/mts/release/bora-1331820/bora/build/esx/release/vmvisor/sys/lib/python2.6/site-packages/pyVmomi/VmomiSupport.py", line 542, in <lambda>
  File "/build/mts/release/bora-1331820/bora/build/esx/release/vmvisor/sys/lib/python2.6/site-packages/pyVmomi/VmomiSupport.py", line 351, in _InvokeMethod 
  File "/build/mts/release/bora-1331820/bora/build/esx/release/vmvisor/sys/lib/python2.6/site-packages/pyVmomi/SoapAdapter.py", line 1231, in InvokeMethod 
pyVmomi.VmomiSupport.NotImplemented: (vmodl.fault.NotImplemented) { 
   dynamicType = <unset>, 
   dynamicProperty = (vmodl.DynamicProperty) [], 
   msg = 'The requested operation is not implemented by the server.', 
   faultCause = <unset>, 
   faultMessage = (vmodl.LocalizableMessage) [] 
} 

Thanks!

**Comment by rreubenur** [comment]
This works for me:
```
    event_filter = vim.event.EventFilterSpec()
    filter_spec_entity = vim.event.EventFilterSpec.ByEntity()
    filter_spec_entity.entity = vm
    filter_spec_entity.recursion = vim.event.EventFilterSpec.RecursionOption.self
    event_filter.entity = filter_spec_entity
    print content.eventManager.QueryEvents(filter=event_filter)
```
