### ISSUE TITLE
content.viewManager.CreateContainerView() returns BadStatusLine : ' ' when trying to access vim.VirtualMachine Managed Object

### ISSUE THREAD

**Issue by prashasthip** [vmware/pyvmomi#317]
When I clone a VM out of a template and try accessing the managed object I encounter this error.

![image](https://cloud.githubusercontent.com/assets/11154612/11432850/06be5f1a-94dc-11e5-80b6-6dc6d3dbded3.png)

**Comment by folti** [comment]
This happens when the server doesn't respond properly to a query in time, and httplib throws a misleading BadStatusLine exception. Retrying the query will usually result in a proper response, or at least something more comprehensible.

Traceback was this:
> 2016-06-27 16:27:25,843 [salt.cloud.cli   ][ERROR   ][10606] There was a profile error: ''
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
>     self.config.get('names')
>   File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1446, in run_profile
>     ret[name] = self.create(vm_)
>   File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
>     output = self.clouds[func](vm_)
>   File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2442, in create
>     data = show_instance(vm_name, call='action')
>   File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1576, in show_instance
>     vm_list = salt.utils.vmware.get_mors_with_properties(_get_si(), vim.VirtualMachine, vm_properties)
>   File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 445, in get_mors_with_properties
>     content = get_content(service_instance, object_type, property_list=property_list, container_ref=container_ref)
>   File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 351, in get_content
>     container_ref = service_instance.content.rootFolder
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 560, in __call__
>     return self.f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 383, in _InvokeAccessor
>     return self._stub.InvokeAccessor(self, info)
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
>     options=self._pcType.RetrieveOptions(maxObjects=1))
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 566, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1255, in InvokeMethod
>     resp = conn.getresponse()
>   File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 415, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
>     raise BadStatusLine(line)
> BadStatusLine: ''

**Comment by tonardo2015** [comment]
@prashasthip @folti Is there some suggestion to fix this issue?
