### ISSUE TITLE
Error using Python3.4 to remove network adapter

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvmomi#328]
I've got an unit test which works fine in python 2.7 and fails in python 3.4 : 

```python
def _remove_network_adapters(self, vm):
        spec = vim.vm.ConfigSpec()
        spec.deviceChange = []
        for dev in vm.config.hardware.device:
            if isinstance(dev, vim.vm.device.VirtualEthernetCard):
                spec.deviceChange.append(
                    devices.remove_network_device_spec(dev))
        the_task = vm.ReconfigVM_Task(spec=spec)
        task.wait_for_task(the_task)

def test_remove_virtual_nic(self):
        folder = "vmwareapi"
        name = "eros-ut01-itg"
        connection = session.connect(settings.ENVIRONMENT)
        vm = connection.find_vm(
            settings.DATACENTER, folder, name)
        if vm is not None:
            if vm.runtime.powerState == 'poweredOn':
                task.wait_for_task(vm.PowerOffVM_Task())
            vm.delete()
        vm = connection.create_vm_from_template(
            name=name,
            template=settings.TEMPLATE,
            datacenter=settings.DATACENTER,
            datastore=settings.DATASTORE,
            cluster=settings.CLUSTER,
            folder=folder,
            power_on=False)
        self.assertIsNotNone(vm)
        self._remove_network_adapters(vm)
        self.assertEqual(0, self._find_ethernet_adapter(vm))

```

the error :

```python
ERROR: test_remove_virtual_nic (vmwareapi.integration_tests.test_vms.ApiVirtualMachineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/Cloud/git/vmware-api/vmwareapi/integration_tests/test_vms.py", line 494, in test_remove_virtual_nic
    self._remove_network_adapters(vm)
  File "/home/vagrant/Cloud/git/vmware-api/vmwareapi/integration_tests/test_vms.py", line 465, in _remove_network_adapters
    the_task = vm.ReconfigVM_Task(spec=spec)
  File "/home/vagrant/Cloud/git/vmware-api/.tox/py34/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 570, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/vagrant/Cloud/git/vmware-api/.tox/py34/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 376, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/vagrant/Cloud/git/vmware-api/.tox/py34/lib/python3.4/site-packages/pyVmomi/SoapAdapter.py", line 1335, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
nose.proxy.vmodl.fault.InvalidRequest: (vmodl.fault.InvalidRequest) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '\nError returned by expat parser: not well-formed (invalid token)\n\nwhile parsing serialized value of type string\nat line 3, column 202\n\nwhile parsing property "label" of static type string\n\nwhile parsing serialized DataObject of type vim.Description\nat line 3, column 190\n\nwhile parsing property "deviceInfo" of static type Description\n\nwhile parsing serialized DataObject of type vim.vm.device.VirtualE1000\nat line 3, column 143\n\nwhile parsing property "device" of static type VirtualDevice\n\nwhile parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec\nat line 3, column 100\n\nwhile parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec\n\nwhile parsing serialized DataObject of type vim.vm.ConfigSpec\nat line 3, column 94\n\nwhile parsing call information for method ReconfigVM_Task\nat line 3, column 14\n\nwhile parsing SOAP body\nat line 3, column 0\n\nwhile parsing SOAP envelope\nat line 2, column 0\n\nwhile parsing HTTP request for method reconfigure\non object of type vim.VirtualMachine\nat line 1, column 0',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

```

**Comment by nlamirault** [comment]
Hi
any news on this Bug ?

**Comment by tianhao64** [comment]
@nlamirault , it's not obvious what went wrong based on the error log. Were you passing any non-ascii chars in the request? 

I will push a couple of python3 related fixes next week. Please give another try after that.

**Comment by nlamirault** [comment]
OK. Non any ascii chars in the request. But perhaps, vcenter use a french configuration. I will try after yours fixes. Thanks

**Comment by nlamirault** [comment]
Any news on this issue ?

**Comment by tianhao64** [comment]
I just pushed a fix to some serialization issues. Can you check if it fix your error? There are a couple of more changes I will submit soon.

**Comment by nlamirault** [comment]
Using the last code from git master, it works fine in Python 3.4.
Great !
Could you please make a new release with this bugfix ?

**Comment by tianhao64** [comment]
@nlamirault Thanks for the confirmation. Yes, I will make a new release once I push out the rest of the changes.

**Comment by nlamirault** [comment]
Do you have an idea of the date of the next release ?
Last stable version is really old (Nov 30, 2015) and a lot of commits are missing ....

**Comment by tianhao64** [comment]
@nlamirault I hope to finish this by end of next week.
