### ISSUE TITLE
bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed'

### ISSUE THREAD

**Issue by smrutim01** [vmware/pyvmomi#370]
SI = connect.SmartConnect(host='172.17.3.183',user='root',pwd='xxxxx',port=443)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vmlib/.local/lib/python2.7/site-packages/pyVim/connect.py", line 663, in SmartConnect
    sslContext)
  File "/home/vmlib/.local/lib/python2.7/site-packages/pyVim/connect.py", line 552, in __FindSupportedVersion
    sslContext)
  File "/home/vmlib/.local/lib/python2.7/site-packages/pyVim/connect.py", line 472, in __GetServiceVersionDescription
    tree = __GetElementTreeFromUrl(url, sslContext)
  File "/home/vmlib/.local/lib/python2.7/site-packages/pyVim/connect.py", line 440, in __GetElementTreeFromUrl
    sock = requests.get(url)
  File "/home/vmlib/.local/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/home/vmlib/.local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vmlib/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vmlib/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/vmlib/.local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by tianhao64** [comment]
@smrutim01 please pass a sslContext to SmartConnect:

import ssl
context = ssl._create_unverified_context()
si = SmartConnect(host=args.host,
                     user=args.user,
                     pwd=password,
                     port=int(args.port),
                     sslContext=context)

**Comment by andrewfraley** [comment]
Does anyone know how to make this work on Python 2.7.5?
