### ISSUE TITLE
Connecting to vCenter 6.0U2 Build 3634794 fails with certificate verify failed

### ISSUE THREAD

**Issue by nvpnathan** [vmware/pyvmomi#444]
$ python hello_world_vcenter.py -s 10.1.1.10 -o 443 -u administrator@vsphere.local -p *****
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Caught vmodl fault : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by nvpnathan** [comment]
Upgraded to pyvmomi-6.0.0.2016.6 and now get the following error.
$ python hello_world_vcenter.py -s 10.1.1.10 -o 443 -u administrator@vsphere.local -p ******
Traceback (most recent call last):
  File "hello_world_vcenter.py", line 104, in <module>
    main()
  File "hello_world_vcenter.py", line 79, in main
    port=int(args.port))
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 786, in SmartConnect
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 671, in __FindSupportedVersion
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 591, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 557, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by tianhao64** [comment]
dup of https://github.com/vmware/pyvmomi/issues/370

**Comment by mo7ssin** [comment]
$ brew update

$ brew install openssl
