### ISSUE TITLE
How do I disable the SSL cert check? --> connect.SmartConnect fails with SSL: CERTIFICATE_VERIFY_FAILED error -- h

### ISSUE THREAD

**Issue by github-12341234** [vmware/pyvmomi#454]
connect.SmartConnect fails with SSL error -- **how do I disable the SSL cert check?**

Run on Python 3.5.2 :: Anaconda 4.1.1 (x86_64)

``````
>>> from pyvim import connect
>>> from pyVmomi import vmidl
>>> from pyVmomi import vim
>>> si = connect.SmartConnect(host=inputs['vcenter_ip'], port=443, user=inputs['vcenter_user'], pwd=inputs['vcenter_password'], service="hosted"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jsmith/anaconda3/lib/python3.5/site-packages/pyvim/connect.py", line 786, in SmartConnect
    sslContext)
  File "/Users/jsmith/anaconda3/lib/python3.5/site-packages/pyvim/connect.py", line 671, in __FindSupportedVersion
    sslContext)
  File "/Users/jsmith/anaconda3/lib/python3.5/site-packages/pyvim/connect.py", line 591, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/Users/jsmith/anaconda3/lib/python3.5/site-packages/pyvim/connect.py", line 557, in __GetElementTree
    conn.request("GET", path)
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 1102, in end headers
    self._send_output(message_body)
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Users/jsmith/anaconda3/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/Users/jsmith/anaconda3/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/Users/jsmith/anaconda3/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/Users/jsmith/anaconda3/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/jsmith/anaconda3/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```)
``````

**Comment by satwikk** [comment]
Use "requests" package.

``` python
import requests

# Write this line before creating pyVmomi session
requests.packages.urllib3.disable_warnings()
```

And all the SSL warnings will be disabled.

**Comment by aapfactory** [comment]
Use SmartConnectNoSSL to bypass SSL check,

```
 service_instance = connect.SmartConnectNoSSL(host=args.host,
                               user=args.user,
                               pwd=args.password,
                               port=int(args.port))

```

**Comment by Andy4081** [comment]
Hi guys, I am very new to Python world. My goal is to collect VMs info (like CPU, RAM usage) from ESXi and was using this link as reference https://virtualwires.wordpress.com/2016/07/25/using-pyvmomi-to-collect-esxi-info

I have both python 2.7 and 3.5 running on Ubuntu box:

`root@ubuntu:~$ python3 --version
Python 3.5.2
root@ubuntu:~$ python --version
Python 2.7.12`

When I run the script using Python 2.7, it gives "SSL: CERTIFICATE_VERIFY_FAILED" error like below:
`root@ubuntu:~$ python esx.py -s 'Host_IP' -u 'user' -p 'pwd'
Traceback (most recent call last):
  File "esx.py", line 33, in <module>
    main()
  File "esx.py", line 19, in main
    si = SmartConnect(host=opts.shost,user=opts.username,pwd=opts.password )
  ...
....
  conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
root@ubuntu:~$`

When I run using Python3 I get syntax error:
`root@ubuntu:~$ python3 esx.py -s 'Host_IP' -u 'user' -p 'pwd'
  File "esx.py", line 25
    print 'The CPU vendor is %s and the model is %s'  %(cpuobj.vendor,cpuobj.description)
                                                   ^
SyntaxError: invalid syntax
root@ubuntu:~$`

The script is the same as shown in the article -
https://virtualwires.wordpress.com/2016/07/25/using-pyvmomi-to-collect-esxi-info

How do I make it work?

**Comment by iahmad-khan** [comment]
I think you should just stick to use python 2.7 ,  because that library is not yet parted to python3

**Comment by iahmad-khan** [comment]
yes , @aapfactory is right , using  smartconnectNoSSL is the solution to your problem in this case.

**Comment by saargrin** [comment]
@aapfactory  thanks for the tip !

**Comment by gaurav-dalvi** [comment]
`python getallvms.py -s hostname -u username -p password -S` did the trick for me .

**Comment by Neurobion** [comment]
https://www.python.org/dev/peps/pep-0476/

**Comment by jasper9** [comment]
I have found that even when using smartconnectNoSSL, I have working syntax for configuring vSwitches and other things, but trying to configure VSAN disks with vsanVcDiskManagementSystem.InitializeDiskMappings gives an SSL error.   Is something hard coded in that module for requiring SSL?

Traceback (most recent call last):
  File "./innkeeper2-pipeline/jobs/conf-vsan-job/conf-vsan-task/conf-vsan.py", line 761, in <module>
    task = vsanVcDiskManagementSystem.InitializeDiskMappings(dm)
  File "/usr/lib64/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib64/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib64/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1319, in InvokeMethod
    conn.request('POST', self.path, req, headers)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1024, in connect
    http_client.HTTPSConnection.connect(self)
  File "/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

**Comment by jasper9** [comment]
Looks like the following combination works for python 3.6, pyvmomi 7.2.1, vsphere 6.5 and 6.7

requests.packages.urllib3.disable_warnings()
ssl._create_default_https_context = ssl._create_unverified_context
context = ssl.create_default_context()
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE

**Comment by nanonyme** [comment]
Meh, you really should have at least internal CA and valid certs for pyvmomi to use. All instructions thus far seem to be about disabling MITM protection for pyvmomi.

**Comment by fafter82** [comment]
you can also..
`import ssl
context = ssl._create_unverified_context()

si = SmartConnect(host=args.host, user=args.user,
               pwd=args.password, sslContext=context)
`

**Comment by xnemanvij** [comment]
> Use SmartConnectNoSSL to bypass SSL check,
> 
> ```
>  service_instance = connect.SmartConnectNoSSL(host=args.host,
>                                user=args.user,
>                                pwd=args.password,
>                                port=int(args.port))
> ```

SmartConnectNoSSL worked for us Thanks

**Comment by gauravchaudhari02** [comment]
```
import urllib3

urllib3.disable_warnings() 
```
