### ISSUE TITLE
Unable to authenticate to a vcenter server using AD account..I am sure I am using right set of login credentials.

### ISSUE THREAD

**Issue by rajenpr** [vmware/pyvmomi#463]
Traceback (most recent call last):
  File "vminfo_quick.py", line 49, in <module>
    port=int(args.port))
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 805, in SmartConnect
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 262, in Connect
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 351, in __Login
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 580, in <lambda>
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1373, in InvokeMethod
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by magykjames** [comment]
It's working for me. You have to pass in the username with the domain as a string in slash notation, like this:
username = 'domain\user'
It might also work with 'user@domain' but I haven't tried that.

**Comment by xayangjing** [comment]
Please try  username='domain\\user'

**Comment by bmw535i** [comment]
xayangjing, solution works with actual domain name, it didn't work for me when using it for vsphere.local/administrator account. Someone else would need to have it confirmed.  I had this issue with vcenter 6.5.

**Comment by manjeetchauhan211** [comment]
It's working for me like  
# python VMware_VM_list.py -s 'hostname.domain.com' -u 'Domain\username' -p 'password'
