### ISSUE TITLE
Exceptions while try to connect sphere.

### ISSUE THREAD

**Issue by DarcyNing** [vmware/pyvmomi#488]
Traceback (most recent call last):
  File "getvnicinfo.py", line 134, in <module>
    sys.exit(main())
  File "getvnicinfo.py", line 123, in main
    port=443)
  File "D:\Program\Python27\lib\site-packages\pyVim\connect.py", line 817, in SmartConnect
    sslContext)
  File "D:\Program\Python27\lib\site-packages\pyVim\connect.py", line 702, in __FindSupportedVersion
    sslContext)
  File "D:\Program\Python27\lib\site-packages\pyVim\connect.py", line 622, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "D:\Program\Python27\lib\site-packages\pyVim\connect.py", line 588, in __GetElementTree
    conn.request("GET", path)
  File "D:\Program\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "D:\Program\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "D:\Program\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "D:\Program\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "D:\Program\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "D:\Program\Python27\lib\httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "D:\Program\Python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "D:\Program\Python27\lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "D:\Program\Python27\lib\ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by sathvikm** [comment]
Hi DarcyNing,

The question is too old. I hope by this time you got the solution. But the answer might be useful for others.

The issue you reported is an SSL certification verification related. Modify you connection code as below 

`
from __future__ import print_function
    from pyVim.connect import SmartConnect, Disconnect
    import argparse
    import atexit
    import getpass
    import ssl


    def GetArgs():
        """Support the command-line arguments listed below."""
        parser = argparse.ArgumentParser(
            description='Process args for retrieving all the Virtual Machines')
        parser.add_argument(
            '-s', '--host', required=True, action='store',
            help='Remote host to connect to'
        )
        parser.add_argument(
            '-o', '--port', type=int, default=443, action='store',
            help='Port to connect on'
        )
        parser.add_argument(
            '-u', '--user', required=True, action='store',
            help='User name to use when connecting to host'
        )
        parser.add_argument(
            '-p', '--password', required=False, action='store',
            help='Password to use when connecting to host'
        )
        parser.add_argument(
            '-v', '--vmname', required=True, action='store',
            help='Provide the VM name for which you snapshot list is printed.'
        )
        args = parser.parse_args()
        return args


    def vcConnect():
        args = GetArgs()
        if args.password:
            password = args.password
        else:
            password = getpass.getpass(
                prompt='Enter password for host %s and '
                'user %s: ' % (args.host, args.user)
            )
        context = None
        if hasattr(ssl, '_create_unverified_context'):
            context = ssl._create_unverified_context()
        si = SmartConnect(
            host=args.host,
            user=args.user,
            pwd=password,
            port=int(args.port),
            sslContext=context)
        if not si:
            print(
                "Could not connect to the specified host using specified ",
                "username and password"
            )

            atexit.register(Disconnect, si)
        else:
            return si

`

Thanks
