### ISSUE TITLE
Failed to connect SPBM API w/[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by lamw** [vmware/pyvmomi#492]
Trying to connect to the SPBM APIs ... but getting the following SSL error which I believe is related to accepting self-sign cert. This is using the latest pyvmomi 6.5

```
Traceback (most recent call last):
  File "pbm.py", line 99, in <module>
    main()
  File "pbm.py", line 95, in main
    pbmSi, pbmContent = GetPbmConnection(si._stub)
  File "pbm.py", line 45, in GetPbmConnection
    pbmContent = pbmSi.RetrieveContent()
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Library/Python/2.7/site-packages/pyVmomi/SoapAdapter.py", line 1323, in InvokeMethod
    conn.request('POST', self.path, req, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/Library/Python/2.7/site-packages/pyVmomi/SoapAdapter.py", line 1024, in connect
    http_client.HTTPSConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

Here's the script:
```
#!/usr/bin/env python

"""
Example using Storage Policy Based Management (SPBM) API
"""

__author__ = 'William Lam'
from pyVmomi import vim, pbm, VmomiSupport
from pyVim.connect import SmartConnect, Disconnect
from requests.packages.urllib3.exceptions import InsecureRequestWarning

import atexit
import argparse
import getpass
import requests
import sys
import ssl

def GetPbmConnection(vpxdStub):
   import Cookie
   import pyVmomi
   sessionCookie = vpxdStub.cookie.split('"')[1]
   httpContext = VmomiSupport.GetHttpContext()
   cookie = Cookie.SimpleCookie()
   cookie["vmware_soap_session"] = sessionCookie
   httpContext["cookies"] = cookie
   VmomiSupport.GetRequestContext()["vcSessionCookie"] = sessionCookie
   hostname = vpxdStub.host.split(":")[0]
   pbmStub = pyVmomi.SoapStubAdapter(host=hostname,
                                     version = "pbm.version.version1",
                                     path = "/pbm/sdk",
                                     poolSize=0)
   pbmSi = pbm.ServiceInstance("ServiceInstance", pbmStub)
   pbmContent = pbmSi.RetrieveContent()

   return (pbmSi, pbmContent)

def GetArgs():
   """
   Supports the command-line arguments listed below.
   """
   parser = argparse.ArgumentParser(
       description='Process args for VSAN SDK sample application')
   parser.add_argument('-s', '--host', required=True, action='store',
                       help='Remote host to connect to')
   parser.add_argument('-o', '--port', type=int, default=443, action='store',
                       help='Port to connect on')
   parser.add_argument('-u', '--user', required=True, action='store',
                       help='User name to use when connecting to host')
   parser.add_argument('-p', '--password', required=False, action='store',
                       help='Password to use when connecting to host')
   args = parser.parse_args()
   return args

#Start program
def main():
   args = GetArgs()
   if args.password:
      password = args.password
   else:
      password = getpass.getpass(prompt='Enter password for host %s and '
                                        'user %s: ' % (args.host,args.user))

   #For python 2.7.9 and later, the defaul SSL conext has more strict
   #connection handshaking rule. We may need turn of the hostname checking
   #and client side cert verification
   context = None
   if sys.version_info[:3] > (2,7,8):
      context = ssl.create_default_context()
      context.check_hostname = False
      context.verify_mode = ssl.CERT_NONE

   # Disabling the annoying InsecureRequestWarning message
   requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

   si = SmartConnect(host=args.host,
                     user=args.user,
                     pwd=password,
                     port=int(args.port),
                     sslContext=context)

   atexit.register(Disconnect, si)

   # Connect to SPBM Endpoint
   pbmSi, pbmContent = GetPbmConnection(si._stub)

# Start program
if __name__ == "__main__":
   main()
```

**Comment by tianhao64** [comment]
Hi @lamw,
You can pass sslContext to SoapStubAdapter to bypass the cert check:

pbmStub = pyVmomi.SoapStubAdapter(host=hostname,
                                     version = "pbm.version.version1",
                                     path = "/pbm/sdk",
                                     poolSize=0,
                                     sslContext=ssl._create_unverified_context())

**Comment by lamw** [comment]
Thanks @tianhao64, that worked
