### ISSUE TITLE
raised unexpected: BadStatusLine("''",)

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi#522]
when i execute some operation by pyvmomi，some error occur like this in the linux(ubuntu 14.04), but work well in the windows ,please help me what is wrong?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/vm-service/branches/dev/vm_service/tasks.py", line 1189, in clone_vm
    conf_vm_net = vc.execute_program_in_vm(target_vm.name, path_to_program, argument, vm_user=vm_user, vm_pwd=vm_pwd)
  File "/var/www/vm-service/branches/dev/vm_service/vSphere_client.py", line 1295, in execute_program_in_vm
    tools_status = vm.guest.toolsStatus
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1324, in InvokeMethod
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by connorwstein** [comment]
+1

**Comment by magykjames** [comment]
I'm getting this same error from checking the session.
>>> si.content.sessionManager.currentSession.key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1320, in InvokeMethod
    resp = conn.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

I'm running this on Red Hat Enterprise Linux 7.2.

**Comment by bobbyscharmann** [comment]
Similar issue in pyvmomi 6.7. Anyone find a resolution?

**Comment by mouhamedfd** [comment]
Check your antivirus (KESL), or your firewall, on Rhel7.2 it could be the source

**Comment by DanielDraganov** [comment]
It looks like a Python 2 related issue.
As of Dec 15, 2022 Python 2.7 is no longer supported. Ref. https://github.com/vmware/pyvmomi/commit/6234051f13627f006edeae753b42e729a3a3f657
This issue is outdated and therefore is closed.
