### ISSUE TITLE
  vmware:  failed to connect: Could not connect to host

### ISSUE THREAD

**Issue by RajaRajan-P** [vmware/pyvmomi#559]
Hi ,

I am getting this error while connecting to my Vcenter.

2017-06-14 15:33:34,713 [salt.cloud.cli   ][INFO    ][33334] salt-cloud starting
_2017-06-14 15:33:34,783 [salt.loader      ][DEBUG   ][33334] **Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/joyent.py", line 63, in <module>
    from Crypto.Hash import SHA256
ImportError: No module named Crypto.Hash**_
2017-06-14 15:33:34,908 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
2017-06-14 15:33:34,908 [salt.utils.lazy  ][DEBUG   ][33334] LazyLoaded parallels.avail_locations
2017-06-14 15:33:34,908 [salt.utils.lazy  ][DEBUG   ][33334] LazyLoaded proxmox.avail_sizes
2017-06-14 15:33:34,909 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
2017-06-14 15:33:34,910 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
2017-06-14 15:33:34,911 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
2017-06-14 15:33:34,912 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
2017-06-14 15:33:34,913 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
2017-06-14 15:33:34,913 [salt.utils.lazy  ][DEBUG   ][33334] LazyLoaded openstack.list_locations
2017-06-14 15:33:34,914 [salt.utils.lazy  ][DEBUG   ][33334] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
2017-06-14 15:33:34,914 [salt.cloud       ][DEBUG   ][33334] Trying to execute 'vmware.test_vcenter_connection' with the following kwargs: {}
2017-06-14 15:33:35,638 [salt.utils.lazy  ][DEBUG   ][33334] LazyLoaded nested.output

**Comment by sathvikm** [comment]
Hi RajaRajan,

From the log which you provided it looks like joyent.py script is failed to load the module called Crypto. Check if the module is installed or not on your system or you can install using "pip install crypto" command.

Thanks
