### ISSUE TITLE
InvokeMethod error when trying to copy disk

### ISSUE THREAD

**Issue by Retenodus** [vmware/pyvmomi#576]
Hello,

I'm trying to copy a disk using VirtualDiskManager.CopyVirtualDisk:

`destSpec = vim.VirtualDiskManager.VirtualDiskSpec()
 destSpec.diskType = "eagerZeroedThick"
 destSpec.adapterType = "busLogic"
 dc = self.get_obj([vim.Datacenter], dc)
 task = vim.VirtualDiskManager.CopyVirtualDisk(
            sourceName=source_path,
            sourceDatacenter=dc,
            destName=dest_path,
            destDatacenter=dc,
            destSpec=destSpec
   )`

Here, sourceDatacenter and desDatacenter are valids, sourceName and destName are strings in the form of "[Datastore] path/to/disk"

I get the following error:

>   File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
>    return self.f(*args, **kwargs)
>TypeError: _InvokeMethod() takes at least 2 arguments (1 given)

I originally used pyvmomi-6.0.0.2016.6 and I upgraded to 6.5.0.2017.5.post1, without any change.

Is there a way I can troubleshoot this ? I tried to find in the documentation what I missed but found nothing, is it a known issue ?

Regards,
Grégoire

**Comment by kofec** [comment]
I also have problem with function. We I use CopyVirtualDisk without "destSpec". All is fine - it is working. Because:
> "The specification of the virtual disk to be created. If not specified the specification of the source disk is used."

```
dest_spec = vim.VirtualDiskManager.VirtualDiskSpec()
dest_spec.diskType = vim.VirtualDiskManager.VirtualDiskType.thin
dest_spec.adapterType = vim.VirtualDiskManager.VirtualDiskAdapterType.lsiLogic
logging.info(dest_spec)
task = disk_manager.CopyVirtualDisk_Task(
    sourceName=source_name,
    sourceDatacenter=source_datacenter,
    destName=dest_name,
    destDatacenter=dest_datacenter)
WaitForTask(task)
return True
```
but when I add specification:
```
dest_spec = vim.VirtualDiskManager.VirtualDiskSpec()
dest_spec.diskType = vim.VirtualDiskManager.VirtualDiskType.thin
dest_spec.adapterType = vim.VirtualDiskManager.VirtualDiskAdapterType.lsiLogic
logging.info(dest_spec)
task = disk_manager.CopyVirtualDisk_Task(
    sourceName=source_name,
    sourceDatacenter=source_datacenter,
    destName=dest_name,
    destDatacenter=dest_datacenter,
    destSpec=dest_spec,
    force=True)
WaitForTask(task)
return True
```
 I have below error:

```
Traceback (most recent call last):
  File "VmwareInstallScripts/vmware.py", line 68, in <module>
    my_testline.clone_vmdk_new()
  File "/home/user/scripts/VmwareInstallScripts/tools/functions.py", line 564, in clone_vmdk_new
    WaitForTask(task)
  File "/home/user/pyvmomi/lib/python3.6/site-packages/pyVim/task.py", line 128, in WaitForTask
    version, state = GetTaskStatus(task, version, pc)
  File "/home/user/pyvmomi/lib/python3.6/site-packages/pyVim/task.py", line 233, in GetTaskStatus
    state = task.info.state
  File "/home/user/pyvmomi/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 700, in __call__
    return self.f(*args, **kwargs)
  File "/home/user/pyvmomi/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 520, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/user/pyvmomi/lib/python3.6/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.Read'
}
(pyvmomi) user@VirtualBox:~/scripts$
```
print my VirtualDiskSpec:

```
  (vim.VirtualDiskManager.VirtualDiskSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   diskType = 'thin',
   adapterType = 'lsiLogic'
}
```
