### ISSUE TITLE
Cannot Execute HostProfile

### ISSUE THREAD

**Issue by tzakrajs** [vmware/pyvmomi#578]
I am attempting to execute a host profile against a host. The API complains that I haven't passed configSpec when I actually have. I haven't made any changes to the require_input (which will become user_input parameter in call to ApplyHostConfig_Task), but that shouldn't stop this call from returning.

Docs:
[applyHostConfiguration vsphere 6.5 docs](https://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.profile.host.ProfileManager.html#applyHostConfiguration)

Here is the code:
```
    def remediate_host(self, host_obj):
        result = self.remote_obj.ExecuteHostProfile(host_obj)
        require_input = result.requireInput
        config_spec = result.configSpec
        profile_manager = self.content.hostProfileManager
        profile_manager.ApplyHostConfig_Task(host_obj, config_spec, require_input)
```

Here is the traceback:
```
Traceback (most recent call last):
  File "configure_vcsa.py", line 12, in <module>
    vcc.run(True)
  File "/root/repos/[REDACTED]/core/vmware/config.py", line 273, in run
    host_profile.remediate_host(host.remote_obj)
  File "/root/repos/[REDACTED]/core/vmware/config.py", line 130, in remediate_host
    profile_manager.ApplyHostConfig_Task(host_obj, config_spec, require_input)
  File "/usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 385, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "/usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 915, in CheckField
    raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "configSpec" not provided (not @optional)
```

When I try to add configSpec as a kwarg to the ApplyHostConfig_Task call, I get this traceback instead:
```
Traceback (most recent call last):
  File "configure_vcsa.py", line 12, in <module>
    vcc.run(True)
  File "/root/repos/SugarAnn/core/vmware/config.py", line 272, in run
    host_profile.remediate_host(host.remote_obj)
  File "/root/repos/SugarAnn/core/vmware/config.py", line 129, in remediate_host
    profile_manager.ApplyHostConfig_Task(host_obj, config_spec, require_input, configSpec=config_spec)
  File "/usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 581, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py", line 384, in _InvokeMethod
    (Capitalize(info.name),  k))
TypeError: ApplyHostConfiguration() got multiple values for keyword argument 'configSpec'
```

**Comment by tzakrajs** [comment]
I think I misunderstood the interface. I am going to close this for now.
