### ISSUE TITLE
Exception:  maximum recursion depth exceeded. 

### ISSUE THREAD

**Issue by sathvikm** [vmware/pyvmomi#584]
Observed below error while running one of my test cases. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sample.py", line 56, in run
    t = si.content.sessionManager.currentSession.key
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1321, in InvokeMethod
    conn = self.GetConnection()
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1395, in GetConnection
    self._CloseIdleConnections()
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1384, in _CloseIdleConnections
    i = self.pool.index((conn, lastAccessTime))
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1060, in __getattr__
    return getattr(self._wrapped, item)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1060, in __getattr__
    return getattr(self._wrapped, item)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1060, in __getattr__
    return getattr(self._wrapped, item)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1060, in __getattr__
    return getattr(self._wrapped, item)

```

The test case does something as below.
1. Connect to vCenter Server using 
`   si = SmartConnect(host=args.host,
                     user=args.user,
                     pwd=password,
                     port=int(args.port),
                     sslContext=context)`
2. List all the VM's in a VCenter
3. Sleep for the 30 minutes 
4. Repeat point 2 and 3 in a loop 

Initially, I observed session time out error. To fix this issue I created a background thread which will check  **si.content.sessionManager.currentSession.key**  for every 10 minutes. The idea here is to get a session hit and keep my session alive.

Using pyvmomi==6.5; VCenter-Server -6.0U2 

Thanks in Advance.

**Comment by tianhao64** [comment]
A similar error(#487) was fixed in v6.5.0.2017.5. Can you upgrade to the latest build and try again?

**Comment by sathvikm** [comment]
Thank you @tianhao after upgrading the pyvmomi to 6.5.0.2017.5 Issue is resolved.

**Comment by tianhao** [comment]
@sathvikm you should thank @tianhao64, not me

**Comment by sathvikm** [comment]
Sorry. Thank you @tianhao64 that was a typo :)

**Comment by tianhao64** [comment]
@tianhao I didn't even notice. Good to meet you :)
