### ISSUE TITLE
get_vm_names.py throws error when connecting to ESXi

### ISSUE THREAD

**Issue by nikhilgeo** [vmware/pyvmomi#592]
python get_vm_names.py -s ESXIP -u root -p myPswd
```
Traceback (most recent call last):
  File "get_vm_names.py", line 86, in <module>
    main()
  File "get_vm_names.py", line 69, in main
    port=int(args.port))
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 888, in SmartConnectNoSSL
    mechanism=mechanism)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
    if __VersionIsSupported(desiredVersion, serviceVersionDescription):
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 683, in __VersionIsSupported
    supportedVersion = versionMap[importElement.get('namespace')[4:]]
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by nikhilgeo** [comment]
pip show pyvmomi
```
Name: pyvmomi
Version: 6.5
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /home/vsecr/.local/lib/python3.5/site-packages
Requires: six, requests
```

**Comment by sathvikm** [comment]
Hi Nikhilgeo, 

I hope the issue is with your script get_vm_names.py. 

Basically, NoneType means that instead of an instance of whatever Class or Object you think you're working with, you've actually got None. That usually means that an assignment or function call up above failed or returned an unexpected result.

Try [getallvms.py](https://github.com/sathvikm/pyvmomi/blob/master/sample/getallvms.py) script from the sample.

**Comment by nikhilgeo** [comment]
IP I was trying to was not of ESXI.
Sorry for the inconvenience.
