### ISSUE TITLE
the error  "can not connect to vcenter " occured frequency!!!!

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi#594]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/vm-service/trunk/vm_service/tasks.py", line 864, in schedule_update_vms_state
    vm_resource = vc.get_vm_resource(vm.name)
  File "/var/www/vm-service/trunk/vm_service/vSphere_client.py", line 1503, in get_vm_resource
    content, error_code, error_msg = self._connect_vcenter()
  File "/var/www/vm-service/trunk/vm_service/vSphere_client.py", line 65, in _connect_vcenter
    port=self.port)
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 590, in SmartConnect
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 234, in Connect
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 319, in __Login
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 307, in __Login
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 566, in <lambda>
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1304, in InvokeMethod
Exception: (DataObject) {

}
^C

**Comment by tianhao64** [comment]
@zhangjianpinghik How to reproduce this error? Please provide steps to reproduce and complete exception.

**Comment by zhangjianpinghik** [comment]
i set a schedule task to excute the get_vm_resource function for updating  vm info to my local db, it is my code:


class vSphere_client(object):

    def __init__(self, host, port, username, password, datacenter): #, heart_beat=180
        """
        实例化vSphere_client
        参数：
            host: vSphere主机地址
            port: vSphere端口
            username: vSphere用户名
            password: vSphere地址
            datacenter: vSphere数据中心名称
        """
        self.host = unicode(host)
        self.port = int(port)
        self.username = unicode(username)
        self.password = unicode(password)
        self.datacenter = unicode(datacenter)

    def _connect_vcenter(self):
        si = connect.SmartConnect(host=self.host,
                                  user=self.username,
                                  pwd=self.password,
                                  port=self.port)
        atexit.register(connect.Disconnect, si)
        try:
            content = si.RetrieveContent()
            return content, error_define_map["NO_ERROR"], ""
        except vmodl.RuntimeFault, ex:
            return False, error_define_map["CONNECT_FAILED"], ex.msg


    def get_vm_resource(self, vm_name, vm_folder=None, is_template=False):
        """
        获取虚拟机的资源及配置信息，
        主要包括：cpu核数、内存大小、mac地址、存储空间大小（单位GB）、ip地址、开机状态等信息
        """
        vm_resource_info = {}
        net_conf_info = []
        content, error_code, error_msg = self._connect_vcenter()
        # content, error_code, error_msg = self._refresh_connection()
        if error_code:
            return None, error_code, error_msg
        ret, error_code, error_msg = self._center_location(content)
        if error_code:
            return None, error_code, error_msg
        vm, error_code, error_msg = self._vm_location(ret, vm_name, vm_folder, is_template=is_template)
        if not vm:
            vm, error_code, error_msg = self._vm_location(ret, vm_name, vm_folder=u"已发现虚拟机", is_template=is_template)
            if error_code:
                return None, error_code, error_msg
        os_info = (vm.summary.config.guestFullName).split("(")
        for item in vm.guest.net:
            if isinstance(item, vim.vm.GuestInfo.NicInfo):
                if "Microsoft" in os_info[0]:
                    dhcp = item.ipConfig.dhcp.ipv4.enable if item.ipConfig else False
                else:
                    dhcp = False
                dns_list = list(dns for dns in item.dnsConfig.ipAddress) if item.dnsConfig else None
                if item.ipConfig:
                    for ip_info in item.ipConfig.ipAddress:
                        if "." in ip_info.ipAddress:
                            ip_addr = ip_info.ipAddress
                            net_conf_info.append(dict(ip_addr=ip_addr, dns=dns_list, mac_addr=item.macAddress, status=item.connected, dhcp=dhcp))
        vm_disk_list = list(int(item.capacityInKB / 1024 / 1024)for item in vm.config.hardware.device if isinstance(item, vim.vm.device.VirtualDisk))
        vm_disk_capacity = reduce(lambda x, y: x + y, vm_disk_list)
        vm_resource_info.update(
            os_name=os_info[0],
            bit=os_info[1][:2],
            status=vm.summary.runtime.powerState,
            memory=vm.summary.config.memorySizeMB,
            cpu_num=vm.summary.config.numCpu,
            disk_size=vm_disk_capacity,
            net_conf_info=net_conf_info,
            is_template=vm.config.template,
            annotation=vm.summary.config.annotation
            )

        return vm_resource_info, 0, 0

**Comment by tianhao64** [comment]
The code looks ok to me. It's not obvious to me what's the problem from the exception. What if you just run: 
"connect.SmartConnect(host=self.host,
                              user=self.username,
                              pwd=self.password,
                              port=self.port)"

What's your pyvmomi, vsphere and python version? Please try to use the latest pyvmomi + latest python.

**Comment by InvalidInterrupt** [comment]
Celery's exception logging strips most error information from pyvmomi's exceptions (due to them being unpickleable). In my experience, the correct exception message can be retrieved from the result backend.

**Comment by zhangjianpinghik** [comment]
@tianhao64 @InvalidInterrupt 

Task vm_service.tasks.schedule_update_vms_state with id 9e557f82-75c3-4ee9-bdec-39f4e289b649 raised exception:
'(DataObject) {\n\n}'


Task was called with args: [] kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/vm-service/trunk/vm_service/tasks.py", line 864, in schedule_update_vms_state
    vm_resource = vc.get_vm_resource(vm.name)
  File "/var/www/vm-service/trunk/vm_service/vSphere_client.py", line 1503, in get_vm_resource
    content, error_code, error_msg = self._connect_vcenter()
  File "/var/www/vm-service/trunk/vm_service/vSphere_client.py", line 65, in _connect_vcenter
    port=self.port)
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 590, in SmartConnect
    path=path)
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 234, in Connect
    keyFile, certFile)
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 319, in __Login
    reraise(vim.fault.HostConnectFault, fault, traceback)
  File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 307, in __Login
    content = si.RetrieveContent()
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 566, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1304, in InvokeMethod
    raise http_client.HTTPException("{0} {1}".format(resp.status, resp.reason))
vim.fault.HostConnectFault: (vim.fault.HostConnectFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '503 Service Unavailable',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [] }

**Comment by zhangjianpinghik** [comment]
@tianhao64 
pyvmomi: Version: 5.5.0.2014.1.1
python: 2.7.6

**Comment by zhangjianpinghik** [comment]
when i use pyvimomi 6.5 ,it can not support ascii, the detail is:
https://github.com/vmware/pyvmomi/issues/519

**Comment by tianhao64** [comment]
@zhangjianpinghik #519 is fixed. Can you upgrade to the latest release?

**Comment by zhangjianpinghik** [comment]
@tianhao64 

[2017-08-29 11:33:35,134: WARNING/Worker-4] Traceback (most recent call last):
[2017-08-29 11:33:35,134: WARNING/Worker-4] File "/var/www/vm-service/branches/dev/vm_service/tasks.py", line 79, in synchronize_all_data_from_vCenter_to_db
[2017-08-29 11:33:35,136: WARNING/Worker-4] vm_resource_info = vc.get_vm_resource(vm_info[0], is_template=vm_info[1])
[2017-08-29 11:33:35,136: WARNING/Worker-4] File "/var/www/vm-service/branches/dev/vm_service/vSphere_client.py", line 1502, in get_vm_resource
[2017-08-29 11:33:35,137: WARNING/Worker-4] content, error_code, error_msg = self._connect_vcenter()
[2017-08-29 11:33:35,137: WARNING/Worker-4] File "/var/www/vm-service/branches/dev/vm_service/vSphere_client.py", line 65, in _connect_vcenter
[2017-08-29 11:33:35,138: WARNING/Worker-4] port=self.port)
[2017-08-29 11:33:35,138: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 590, in SmartConnect
[2017-08-29 11:33:35,139: WARNING/Worker-4] path=path)
[2017-08-29 11:33:35,139: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 234, in Connect
[2017-08-29 11:33:35,139: WARNING/Worker-4] keyFile, certFile)
[2017-08-29 11:33:35,139: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 319, in __Login
[2017-08-29 11:33:35,140: WARNING/Worker-4] reraise(vim.fault.HostConnectFault, fault, traceback)
[2017-08-29 11:33:35,140: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVim/connect.py", line 307, in __Login
[2017-08-29 11:33:35,140: WARNING/Worker-4] content = si.RetrieveContent()
[2017-08-29 11:33:35,140: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 566, in <lambda>
[2017-08-29 11:33:35,142: WARNING/Worker-4] self.f(*(self.args + (obj,) + args), **kwargs)
[2017-08-29 11:33:35,142: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
[2017-08-29 11:33:35,142: WARNING/Worker-4] return self._stub.InvokeMethod(self, info, args)
[2017-08-29 11:33:35,142: WARNING/Worker-4] File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1304, in InvokeMethod
[2017-08-29 11:33:35,145: WARNING/Worker-4] raise http_client.HTTPException("{0} {1}".format(resp.status, resp.reason))
[2017-08-29 11:33:35,145: WARNING/Worker-4] vim.fault.HostConnectFault: (vim.fault.HostConnectFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '503 Service Unavailable',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
