### ISSUE TITLE
Increase capacity of disk of  thick provisioned eager zeroed ends up with disk type thick provisioned lazy zeroed

### ISSUE THREAD

**Issue by FrankCRoth** [vmware/pyvmomi#648]
Hi all,
I am trying to extend a disk with reconfigure_vm of type thick provisioned eager zeroed but afterwards the disk type is always changed to thick provisioned lazy zeroed. Please see code snipped below:

        spec = vim.vm.ConfigSpec()
        disk_devices = get_disk_devices(vm)
        vdevice_spec = vim.vm.device.VirtualDeviceSpec()
        disk_spec = disk_devices[0]
        disk_spec.capacityInKB = 100 * 1024 * 1024
        vdevice_spec.device = disk_spec
        vdevice_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.edit
        spec.deviceChange = [vdevice_spec]
        self.reconfigure_vm(vm, spec)

Remark: The get_disk_device gets all disk devices from the vm_object. Only the first one in the list gets extended.

**Comment by prziborowski** [comment]
I believe only new disks get eagerly zereoed when they are created. There is no real configuration in the disk to tell it it is eager/lazy.
If the VM is powered off, you can explicitly have it zeroed.
```
from pyVim.task import WaitForTask
si # is your service instance
disk_path = disk_spec.backing.fileName
vdm = si.content.virtualDiskManager
WaitForTask(vdm.EagerZeroVirtualDisk(disk_path, datacenter))
``` 

If you don't know the datacenter of the VM/disk, you could recurse vm.parent until you reach a datacenter, e.g.
```
def get_dc(obj):
   parent = obj.parent
   while not isinstance(parent, vim.Datacenter):
      parent = parent.parent
   return parent
```

Hmm, but re-reading the docs on the eagerlyScrub property seems to imply you could set it on an edit:
```
If this flag is unset or set to false when creating a new disk, the disk scrubbing policy will be 
decided by the filesystem. If this flag is unset or set to false when editing an existing disk,
it is ignored. When returned as part of a ConfigInfo, this property may be unset if its value
is unknown.
```
So also confirm you do:
```disk_spec.backing.eagerlyScrub = True```

**Comment by FrankCRoth** [comment]
I also tried EagerZeroVirtualDisk, the task does take very long and returns without errors, though afterwards the disk backing eagerlyScub is not set and on the GUI it disk type is still thick provisioned lazy zeroed.

In addition the setting backing.eagerlyScub appears to have no impact during disk config change of the VM. It is always unset, even though if it was True before.

**Comment by FrankCRoth** [comment]
Could resolve the issue, though not in one call. After the disk size is increased using reconfigure task you also need to run the EagerZeroVirtual Disk command:

`WaitForTask(vdm.EagerZeroVirtualDisk(disk_path, datacenter))`

and afterwards refresh the disk object and run the reconfigure task again setting eagerlyScrub to True again.

`disk_spec.backing.eagerlyScrub = True`

Below is code-snip example:

        disk = None
        for device in vm.config.hardware.device:
            if isinstance(device, vim.vm.device.VirtualDisk):
                disk = device
                break
        if disk is None:
            raise Exception("Failed to find disk for VM")
        disk.capacityInKB = size * 1024 * 1024
        spec = vim.vm.ConfigSpec()
        devSpec = vim.vm.device.VirtualDeviceSpec(device=disk, operation="edit")
        spec.deviceChange.append(devSpec)
        if not (self.reconfigure_vm(vm, spec)):
            vm.Destroy_Task()
            raise Exception("Failed to extend disk")

        # To zero out disk afterwards for eagerly scrubbing
        print("Zero out disk")
        disk_manager = self.content.virtualDiskManager
        disk_manager.EagerZeroVirtualDisk_Task(disk.backing.fileName, disk.backing.datastore.parent.parent)
        
        # Write back eagerly scrub to configuration
        # Need to refresh object first
        vm_object_refresh = self.get_obj([vim.VirtualMachine], vm.name)
        for device in vm_object_refresh.config.hardware.device:
            if isinstance(device, vim.vm.device.VirtualDisk):
                disk_refresh = device
                break
        if not disk_refresh.backing.eagerlyScrub:
            print("Scrubbing not set correctly, will set scrubbing on disk.")
            disk_refresh.backing.eagerlyScrub = True
            spec = vim.vm.ConfigSpec()
            devSpec = vim.vm.device.VirtualDeviceSpec(device=disk_refresh, operation="edit")
            spec.deviceChange.append(devSpec)
            self.monitor_task(vm_object_refresh.ReconfigVM_Task(spec=spec))

**Comment by 5t4rdu5t** [comment]
Hi, can someone correct the full code to run from the last snippet from @FrankCRoth please ?


    #!/usr/bin/python3
    
    import atexit
    import hashlib
    import json
    import sys
    import random
    import time
    import ssl
    
    import atexit
    
    from pyVim.connect import SmartConnect, Disconnect
    
    import requests
    from pyVim import connect
    from pyVmomi import vim
    
    from tools import cli
    from tools import tasks
    
    def get_args():
        """
        Use the tools.cli methods and then add a few more arguments.
        """
        parser = cli.build_arg_parser()
    
        parser.add_argument('-n', '--name',
                            required=True,
                            action='store',
                            help='VM name')
    
        parser.add_argument('-d', '--datastore',
                            required=True,
                            action='store',
                            help='Name of Datastore to create VM in')
    
        parser.add_argument('--disk-type',
                            required=False,
                            action='store',
                            default='thin',
                            choices=['thick', 'thin'],
                            help="'thick' (classic vCenter) or 'thin' (Stark)")
    
        parser.add_argument('--disk-size',
                            type=int,
                            required=True,
                            action='store',
                            help='disk size, in GB, to add to the VM')
    
    
        args = parser.parse_args()
        print(args)
    
    
        return cli.prompt_for_password(args)
    
    
    def get_vm_uuid(virtual_machine):
        summary = virtual_machine.summary
        #return { 'name': summary.config.name, 'uuid': summary.config.instanceUuid }
        return { 'name': summary.config.name, 'uuid': summary.config.uuid }
    
    def get_obj(content, vimtype, name):
        obj = None
        container = content.viewManager.CreateContainerView(
            content.rootFolder, vimtype, True)
        for c in container.view:
            if c.name == name:
                obj = c
                break
        return obj
    
    def grow_disk(vm, si, disk_size, disk_type):   
        disk = None
        for device in vm.config.hardware.device:
            if isinstance(device, vim.vm.device.VirtualDisk):
                disk = device
                break
        if disk is None:
            raise Exception("Failed to find disk for VM")
        disk.capacityInKB = disk_size * 1024 * 1024
        spec = vim.vm.ConfigSpec()
        devSpec = vim.vm.device.VirtualDeviceSpec(device=disk, operation="edit")
        spec.deviceChange.append(devSpec)
        if not (self.reconfigure_vm(vm, spec)):
            vm.Destroy_Task()
            raise Exception("Failed to extend disk")
    
        # To zero out disk afterwards for eagerly scrubbing
        print("Zero out disk")
        disk_manager = self.content.virtualDiskManager
        disk_manager.EagerZeroVirtualDisk_Task(disk.backing.fileName, disk.backing.datastore.parent.parent)
        
        # Write back eagerly scrub to configuration
        # Need to refresh object first
        vm_object_refresh = self.get_obj([vim.VirtualMachine], vm.name)
        for device in vm_object_refresh.config.hardware.device:
            if isinstance(device, vim.vm.device.VirtualDisk):
                disk_refresh = device
                break
        if not disk_refresh.backing.eagerlyScrub:
            print("Scrubbing not set correctly, will set scrubbing on disk.")
            disk_refresh.backing.eagerlyScrub = True
            spec = vim.vm.ConfigSpec()
            devSpec = vim.vm.device.VirtualDeviceSpec(device=disk_refresh, operation="edit")
            spec.deviceChange.append(devSpec)
            self.monitor_task(vm_object_refresh.ReconfigVM_Task(spec=spec))
    
    def main():
        """
        Simple command-line program for extending a virtual disk
        """
    
        args = get_args()
    
        # connect to vc
        try:
            default_context = ssl._create_default_https_context
            ssl._create_default_https_context = ssl._create_unverified_context
            service_instance = SmartConnect(
                host=args.host,
                user=args.user,
                pwd=args.password
            )
            ssl._create_default_https_context = default_context
        except Exception as exc:
            if isinstance(exc, vim.fault.HostConnectFault) and '[SSL: CERTIFICATE_VERIFY_FAILED]' in exc.msg:
                try:
                    default_context = ssl._create_default_https_context
                    ssl._create_default_https_context = ssl._create_unverified_context
                    si = SmartConnect(
                        host=args.host,
                        user=args.user,
                        pwd=args.password,
                    )
                    ssl._create_default_https_context = default_context
                except Exception as exc1:
                    raise Exception(exc1)
            else:
                raise Exception(exc)
    
        if not service_instance:
            print("Could not connect to the specified host using specified "
                  "username and password")
            return -1
    
        atexit.register(connect.Disconnect, service_instance)
    
        content = service_instance.RetrieveContent()
        datacenter = content.rootFolder.childEntity[0]
        vmfolder = datacenter.vmFolder
        hosts = datacenter.hostFolder.childEntity
    
        # retrieve VM UUID by name
        content = service_instance.RetrieveContent()
        container = content.rootFolder  # starting point to look into
        viewType = [vim.VirtualMachine]  # object types to look for
        recursive = True  # whether we should look into it recursively
        containerView = content.viewManager.CreateContainerView(
            container, viewType, recursive)
    
        children = containerView.view
        for child in children:
            res = get_vm_uuid(child)
            if (args.name == res['name']):
                uuid = res['uuid']
                break
    
        vm = None
        if uuid:
            search_index = service_instance.content.searchIndex
            vm = search_index.FindByUuid(None, uuid, True)
        elif args.vm_name:
            content = service_instance.RetrieveContent()
            vm = get_obj(content, [vim.VirtualMachine], args.vm_name)
    
        content = service_instance.RetrieveContent()
        vm = get_obj(content, [vim.VirtualMachine], args.name)
    
        if vm:
            grow_disk(vm, service_instance, args.disk_size, args.disk_type)
        else:
            print("VM not found")
    
    
        return 0
    
    if __name__ == "__main__":
        main()

This is a script added to samples directory from [pyvmomi-community-samples repository](https://github.com/vmware/pyvmomi-community-samples.git)

Usage : 

    python3 samples/resize_disk.py -s vc1.example.com -u me -n VM-NAME -d LUN_100 --disk-type thick --disk-size 30

I have the following error when I run the whole script : 

    Traceback (most recent call last):
      File "samples/zeroed_eager_thick_disk_clean.py", line 193, in <module>
        main()
      File "samples/zeroed_eager_thick_disk_clean.py", line 185, in main
        grow_disk(vm, service_instance, args.disk_size, args.disk_type)
      File "samples/zeroed_eager_thick_disk_clean.py", line 89, in grow_disk
        if not (self.reconfigure_vm(vm, spec)):
    NameError: global name 'self' is not defined
