### ISSUE TITLE
Error when trying to access the EAM 

### ISSUE THREAD

**Issue by arnaudcoquelet** [vmware/pyvmomi#657]
All,

I'm try to get all the EAM Agencies available on a vcenter instance using the eam module, but I got the following login error:

```
Traceback (most recent call last):
  File "getEamAgency.py", line 65, in <module>
    main()
  File "getEamAgency.py", line 61, in main
    (eamCx, eamAgencies) = GetEamAgencies(si._stub, context)
  File "getEamAgency.py", line 35, in GetEamAgencies
    eamAgencies = eamCx.QueryAgency()
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidLogin: (eam.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

I reuse the same logic as to connect to the spbm sdk, but that does not seems to work.
How should we login to the EAM SDK ?
(note, same code connecting to the spbm api works).

Here is my code example:
```python
#!/usr/bin/env python

from pyVmomi import vim, eam, VmomiSupport
from pyVim.connect import SmartConnect, Disconnect
from requests.packages.urllib3.exceptions import InsecureRequestWarning

import atexit
import argparse
import getpass
import requests
import sys
import ssl

def GetEamAgencies(vpxdStub, sslContext):
   import Cookie
   import pyVmomi
  
   sessionCookie = vpxdStub.cookie.split('"')[1]
   httpContext = VmomiSupport.GetHttpContext()
   cookie = Cookie.SimpleCookie()
   cookie["vmware_soap_session"] = sessionCookie
   httpContext["cookies"] = cookie
   VmomiSupport.GetRequestContext()["vcSessionCookie"] = sessionCookie
   hostname = vpxdStub.host.split(":")[0]
   
   eamStub = pyVmomi.SoapStubAdapter(host=hostname,
                                     version = "eam.version.version1",
                                     path = "/eam/sdk",
                                     poolSize=0,
                                     sslContext=sslContext)
   eamCx = eam.EsxAgentManager("EsxAgentManager", eamStub)
   eamAgencies = eamCx.QueryAgency()

   return (eamCx, eamAgencies)


#Start program
def main():
    host="vcenter"
    user="user"
    password="password"

    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    
    # Disabling the annoying InsecureRequestWarning message
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
    
    si = SmartConnect(host=host,
                      user=user,
                      pwd=password,
                      sslContext=context)
    
    atexit.register(Disconnect, si)
    
    # Connect to EAM Endpoint
    (eamCx, eamAgencies) = GetEamAgencies(si._stub, context)

# Start program
if __name__ == "__main__":
    main()
```

**Comment by prziborowski** [comment]
I don't know if you need to do all of that cookie parsing, etc.
How about:
```
def GetEamAgencies(vpxdStub, sslContext):
   hostname = vpxdStub.host.split(":")[0]
   
   eamStub = pyVmomi.SoapStubAdapter(host=hostname,
                                     version = "eam.version.version1",
                                     path = "/eam/sdk",
                                     poolSize=0,
                                     sslContext=sslContext)
   eamStub.cookie = vpxdStub.cookie
   eamCx = eam.EsxAgentManager("EsxAgentManager", eamStub)
   eamAgencies = eamCx.QueryAgency()

   return (eamCx, eamAgencies)
```

**Comment by arnaudcoquelet** [comment]
I spent my weekend fighting the issue .... and it was that simple :-)

I stupidly followed a previous example (the one with the spdm connection)...


Thanks a lot @prziborowski , that works!!!

**Comment by amudhar** [comment]
@arnaudcoquelet, I am trying to connect to EsxAgentManager and Create Agency and AgentVMs.
From the documentation, to Create Agency, I should be logged in as a vcenter extension.
Does your above code connect to EsxAgentManager and allow CreateAgency()?
Can you please share if you have  sample code.

Thanks much,
Amudha

**Comment by arnaudcoquelet** [comment]
@amudhar , the code above + the fix provided by @prziborowski only connect to the EsxAgentManager and get an already created Agency.

I do not have any sample that would be creating an Agency.

**Comment by amudhar** [comment]
Thanks @arnaudcoquelet. I was able to create Agencies.
