### ISSUE TITLE
vCenter 6.7 connectivity broken with pyvmomi

### ISSUE THREAD

**Issue by harish-kumar-nvs-kakumanu** [vmware/pyvmomi#660]
I am trying to run pyvmomi samples with vcenter 6.7 and it fails in the connection phase to establish a connection.  

When will the pyvmomi support vCenter 6.7 ?

I get the following error when i run the samples/getallvms.py.

pydev debugger: starting (pid: 26625)
Traceback (most recent call last):
  File "/opt/eclipse/plugins/org.python.pydev_5.5.0.201701191708/pysrc/pydevd.py", line 1537, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/eclipse/plugins/org.python.pydev_5.5.0.201701191708/pysrc/pydevd.py", line 976, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/eclipse/plugins/org.python.pydev_5.5.0.201701191708/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/workspace/voyage/hpov4vc_server_git/ovm/src/vmware/getallvms.py", line 129, in <module>
    main()
  File "/workspace/voyage/hpov4vc_server_git/ovm/src/vmware/getallvms.py", line 109, in main
    sslContext=context)
  File "/root/ovm_env/lib/python3.6/site-packages/pyVim/connect.py", line 817, in SmartConnect
    sslContext)
  File "/root/ovm_env/lib/python3.6/site-packages/pyVim/connect.py", line 702, in __FindSupportedVersion
    sslContext)
  File "/root/ovm_env/lib/python3.6/site-packages/pyVim/connect.py", line 622, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/root/ovm_env/lib/python3.6/site-packages/pyVim/connect.py", line 588, in __GetElementTree
    conn.request("GET", path)
  File "/home/python3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/python3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/python3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/python3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/python3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/python3.6/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/python3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/python3.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/python3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by harish-kumar-nvs-kakumanu** [comment]
yeap...its working. network issue in my place.

**Comment by mabazyar** [comment]
Thanks for providing the code. 

the following is left out on top to have the code run.
``
import atexit
``
