### ISSUE TITLE
Failed to change hostsystem's advance option in Python3

### ISSUE THREAD

**Issue by Akasurde** [vmware/pyvmomi#682]
I using following code to change advance option of Host Systems - 

```python
from pyVim.connect import SmartConnect, Disconnect
import ssl
import atexit
from pyVmomi import vim, vmodl
import time


def connect():
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE

    si = SmartConnect(host='xx.xx.xx.xx', user='administrator@vsphere.local', pwd='password', port=443, sslContext=context)
    atexit.register(Disconnect, si)
    content = si.RetrieveContent()
    return content

def get_obj(content, vimtype, name):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    if name in ['', None]:
        obj = []
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj.append(c)

    container.Destroy()
    return obj

content = connect()

host = get_obj(content, [vim.HostSystem], None)[0]
option_manager = host.configManager.advancedOption
option_manager.UpdateOptions(changedValue=[vim.option.OptionValue(key='UserVars.ESXiShellInteractiveTimeOut', value=long(11))])
for option in option_manager.QueryOptions():
    if option.key == 'UserVars.ESXiShellInteractiveTimeOut':
        print(option.value)
```

This code works perfectly fine in Python 2, but in Python 3, `long` is merged into `int` so raises error.
If I try to typecast value using `int` then it fails with following error - 

```
python host_config.py
Traceback (most recent call last):
  File "host_config.py", line 45, in <module>
    option_manager.UpdateOptions(changedValue=[vim.option.OptionValue(key='UserVars.ESXiShellInteractiveTimeOut', value=int(11))])
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: ',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = <unset>
}
```

I am using Python3.6 and Pyvmomi 6.7.0.

Can someone point me in right direction to use this API ?

**Comment by prziborowski** [comment]
Can you see if https://github.com/vmware/pyvmomi-community-samples/issues/346#issuecomment-295119717 helps you?

**Comment by Akasurde** [comment]
@prziborowski Thanks for the link. I should have searched more before putting the issue. Anyways, it works for me. 

For posterity - 

```python
from pyVim.connect import SmartConnect, Disconnect
import ssl
import atexit
from pyVmomi import vim, vmodl, VmomiSupport
import time


def connect():
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE

    si = SmartConnect(host='xx.xx.xx.xx', user='administrator@vsphere.local', pwd='password', port=443, sslContext=context)
    atexit.register(Disconnect, si)
    content = si.RetrieveContent()
    return content

def get_obj(content, vimtype, name):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    if name in ['', None]:
        obj = []
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj.append(c)

    container.Destroy()
    return obj

content = connect()

host = get_obj(content, [vim.HostSystem], None)[0]
option_manager = host.configManager.advancedOption
option = vim.option.OptionValue()
option.key = 'UserVars.ESXiShellInteractiveTimeOut'
option.value = VmomiSupport.vmodlTypes['long'](12)
option_manager.UpdateOptions(changedValue=[option])
for option in option_manager.QueryOptions():
    if option.key == 'UserVars.ESXiShellInteractiveTimeOut':
        print(option.value)
```

**Comment by zzh1989829** [comment]
pyVmomi.types.int(1) works for me
