### ISSUE TITLE
Error when connecting to vCenter 6.7

### ISSUE THREAD

**Issue by waldirio** [vmware/pyvmomi#694]
Hello all, good morning

I'm trying to connect on vCenter 6.7 using pyvmomi, so below one simple example
```
#!/usr/bin/env python 

from corerv import *
import requests

from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
import ssl

def main():
    print("Reading the conf file")

    obj = coreCode()
    conn = obj.read_conf_file()
    
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password)

if __name__ == "__main__":
    main()
```

Then on scenario above I got the message below
```
Reading the conf file
Traceback (most recent call last):
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 27, in <module>
    main()
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 22, in main
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 770, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1024, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:858)
```

Then I saw some infos / posts related to define the sslContext and some fixes related to that, then

```
#!/usr/bin/env python 

from corerv import *
import requests

from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
import ssl


def main():
    print("Reading the conf file")

    obj = coreCode()
    conn = obj.read_conf_file()

    
    sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    sslContext.verify_mode = ssl.CERT_NONE
    
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password, sslContext=sslContext)
    

if __name__ == "__main__":
    main()
```

Now I'm facing another issue
```
Reading the conf file
Traceback (most recent call last):
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 26, in <module>
    main()
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 22, in main
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password, sslContext=sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 770, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1024, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

Appreciate your help.

Note. Just one complement, tested on Python 2.7 and 3.6, same result.

Waldirio

**Comment by waldirio** [comment]
Hello all

Following the advice from link [1], I'm facing another issue, according below

Code
///
#!/usr/bin/env python 

from corerv import *
import requests

from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
import ssl


def main():
    print("Reading the conf file")

    obj = coreCode()
    conn = obj.read_conf_file()

    
    sslContext = ssl._create_unverified_context()
        
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password, sslContext=sslContext)
    

if __name__ == "__main__":
    main()
///

Result
///
Reading the conf file
Traceback (most recent call last):
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 25, in <module>
    main()
  File "/home/wpinheir/code/rvtools/rvtools/rvtools.py", line 21, in main
    si = connect.SmartConnect(host=conn._vcenter,user=conn._username,pwd=conn._password, sslContext=sslContext)
  File "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 838, in SmartConnect
    raise Exception("%s:%s is not a VIM server" % (host, port))
Exception: <vcenter fqdn here>:443 is not a VIM server
///

Thanks or your help

[1]. https://github.com/vmware/pyvmomi/commit/92c1de5056be7c5390ac2a28eb08ad939a4b7cdd

**Comment by pgbidkar** [comment]
Hi @waldirio ,
Does your conn._vcenter contains port number as well? 
if Your port is not your port is not 443, please pass port number explicitly to SmartConnect()
connect.SmartConnect(host=conn._vcenter,, port=<>, user=conn._username,pwd=conn._password, sslContext=sslContext)
Thanks

**Comment by waldirio** [comment]
Hello @pgbidkar, good morning

Thanks for your reply, doing the debug process I can see the port as the path */sdk* is added automatically when calling the pyvmomi internal code [1] btw I added as well the port, same result.

[1]. "/home/wpinheir/.virtualenvs/rvtools/lib/python3.6/site-packages/pyVim/connect.py", line 838

**Comment by pgbidkar** [comment]
@waldirio Sorry I didnt get what you meant by "I can see the port as the path /sdk is added automatically when calling the pyvmomi internal code"

Please check if conn._vcenter is getting populated correctly?

**Comment by waldirio** [comment]
Hello @pgbidkar, good afternoon

Thanks for your reply, today collecting more information just to update here the code works. :disappointed: , then I was check what is going on. On the vCenter which I'm testing they got disk full *during the weekend* and was fixed today early :smile:, then this is the reason.

Using
```
   sslContext = ssl._create_unverified_context()
```
or
```
    sslContext = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    sslContext.verify_mode = ssl.CERT_NONE
```
Worked as well.

Thank you so much.
Waldirio
