### ISSUE TITLE
how to set the ipmi by the HostIpmiInfo

### ISSUE THREAD

**Issue by CengSin** [vmware/pyvmomi#718]
my code:
```python
    updateIpmi = vim.host.IpmiInfo("HostIpmiInfo", [bmcIpAddress, bmcMacAddress, login, password])
    host.UpdateIpmi(updateIpmi)
```
the exception information:
```shell
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Administrator/PycharmProjects/vmware_esxi_api/src/esxi.py", line 48, in <module>
    updateIpmi = vim.host.IpmiInfo(bmcIpAddress, bmcMacAddress, login, password)
TypeError: __init__() takes exactly 1 argument (5 given)
```

**Comment by prziborowski** [comment]
I usually use named parameters:
```
    updateIpmi = vim.host.IpmiInfo(bmcIpAddress=bmcIpAddress, bmcMacAddress=bmcMacAddress,
                                   login=login, password=password)
    host.UpdateIpmi(updateIpmi)

```

**Comment by CengSin** [comment]
@prziborowski thx
