### ISSUE TITLE
Unable to login to ESXi host, while logging in to vCenter just fine

### ISSUE THREAD

**Issue by dmfigol** [vmware/pyvmomi#724]
I am trying to login to ESXi Host and this is what I see:
```
Traceback (most recent call last):
  File "esxi_helper.py", line 253, in <module>
    main()
  File "esxi_helper.py", line 246, in main
    esxi_content, esxi_connector = connect2vsphere(host=config("ESXI_HOST"), user=config("ESXI_USERNAME"), pwd=config("ESXI_PASSWORD"), port=443)
  File "esxi_helper.py", line 238, in connect2vsphere
    esxi_connector = SmartConnectNoSSL(host=host, user=user, pwd=pwd, port=port)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVim/connect.py", line 888, in SmartConnectNoSSL
    mechanism=mechanism)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVim/connect.py", line 856, in SmartConnect
    mechanism=mechanism)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVim/connect.py", line 266, in Connect
    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVim/connect.py", line 390, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Users/dmfigol/work/scripts/vmware/.venv/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
```
Logging in to vCenter works just fine.
I was googling, but haven't found what I was doing wrong.

**Comment by gaurav-dalvi** [comment]
`python3 getallvms.py -s hostip/name -u username -p password`
https://github.com/vmware/pyvmomi/blob/master/sample/getallvms.py
on this file with latest version `6.7.0.2018.9` worked for me. If you get SSL error try -S option above

**Comment by jeking3** [comment]
```
   msg = 'Cannot complete login due to an incorrect user name or password.',
```

ESXi and vCenter use different authentication.  
Did you want to log into ESXi as "root" perhaps?

**Comment by venugopalsjce** [comment]
I am also facing this problem. Not sure, what's going wrong. Tried with -s option as well, no luck.
Please help resolve this.

`
Traceback (most recent call last):
  File "getallvms.py", line 129, in <module>
  File "getallvms.py", line 109, in main
  File "pyVim\connect.py", line 856, in SmartConnect
  File "pyVim\connect.py", line 266, in Connect
  File "pyVim\connect.py", line 390, in __Login
  File "pyVmomi\VmomiSupport.py", line 706, in <lambda>
  File "pyVmomi\VmomiSupport.py", line 512, in _InvokeMethod
  File "pyVmomi\SoapAdapter.py", line 1374, in InvokeMethod
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
[41108] Failed to execute script getallvms

`

Thanks,
Venu

**Comment by jeking3** [comment]
ESXi and vCenter use different authentication.
Did you want to log into ESXi as "root" perhaps?

**Comment by venugopalsjce** [comment]
Yes, I am trying to log in to ESXi and retrieve all its guest VMs to ascertain their last logon time.
What am I missing here?

**Comment by houcinedz** [comment]
from pyvim.connect import SmartConnectNoSSL, Disconnect

import atexit

si = SmartConnectNoSSL(host='******', user='*******', pwd='******', port=443)
atexit.register(Disconnect, si)
content = si.RetrieveContent()
print content




### **_---------------------------------------i have problem after runing the code------ python2. ------------------_**






Traceback (most recent call last):
  File "C:/Users/power/PycharmProjects/vSphere/test.py", line 5, in <module>
    si = SmartConnectNoSSL(host='*********', user='********', pwd='********', port=443)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 888, in SmartConnectNoSSL
    mechanism=mechanism)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 856, in SmartConnect
    mechanism=mechanism)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 266, in Connect
    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 390, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "C:\Python27\lib\site-packages\pyVmomi\SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by pgbidkar** [comment]
@houcinedz Please can try printing UserName & Password before passing as prams to API?  I face this error because of special chars in UserName or Password which need to be escaped.

**Comment by houcinedz** [comment]
i have special chars **" ! "** but i print username and password but always the same prblm

**Comment by pgbidkar** [comment]
Please can you try escaping the special char '!'.

**Comment by houcinedz** [comment]
is that @vsphere.local  at the end od username ?

**Comment by pgbidkar** [comment]
Yes xxx@vsphere.local is the correct username. If You are passing value before " @ " then it is not correct username

**Comment by deajan** [comment]
Same thing with character `#` in passwords it seems...

**Comment by nfourniol** [comment]
I'm facing the same problem, what I notice is that it works perfectly with ESXi 6.5.0 and ESXi 5.5.0
But it fails with ESXi 6.7.0.

It really seems to be linked to ESXi 6.7.0

**Comment by deajan** [comment]
> I'm facing the same problem, what I notice is that it works perfectly with ESXi 6.5.0 and ESXi 5.5.0 But it fails with ESXi 6.7.0.
> 
> It really seems to be linked to ESXi 6.7.0
> 
> I use pyVim.connect from pyVmomi 7.0.2

Indeed, 6.5 worked for me with '#' in my passwords. On 6.7, I added '@' which works.

**Comment by nfourniol** [comment]
I solved the problem in my case (because of a copy/paste from Internet) :

``
sslCtx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
sslCtx.verify_mode = ssl.CERT_NONE

svcInst = connect.SmartConnect(............., sslContext=sslCtx)
``
by

``
sslCtx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
sslCtx.verify_mode = ssl.CERT_NONE

svcInst = connect.SmartConnect(............., sslContext=sslCtx)
``

Or you can also use : 
``
sslCtx = ssl._create_unverified_context()

svcInst = connect.SmartConnect(............., sslContext=sslCtx
``

**Comment by jdptechnc** [comment]
I have the same issue with a known good password that has a '^' character in it.  Using vSphere 7.0.3 and pyvmomi 8.0.0.1.1.
