### ISSUE TITLE
Login to vcenter using SSO token

### ISSUE THREAD

**Issue by gaurav-dalvi** [vmware/pyvmomi#727]
Is there any way I can login to vcenter using SSO token ? `vmware_soap_session` and not using username and password ? 

We can login using token in https://github.com/vmware/govmomi but could not find a way to do in python library. 

Any help is highly appreciated.

**Comment by gaurav-dalvi** [comment]
I tried in both functions : 
https://github.com/vmware/pyvmomi/blob/master/pyVim/connect.py#L776
https://github.com/vmware/pyvmomi/blob/master/pyVim/connect.py#L858

passing `pwd=None` , `b64token = base 64 encoded token string A`
string A = e'"vmware_soap_session=\"SSO token here\"; '
and `mechanism=sspi` But it still asks for password.

**Comment by gaurav-dalvi** [comment]
I tried getallvms.py from this repo and changed code bit to use token instead of password
I get this error.
```
Traceback (most recent call last):
  File "getallvms.py", line 134, in <module>
    main()
  File "getallvms.py", line 114, in main
    b64token=t)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVim/connect.py", line 856, in SmartConnect
    mechanism=mechanism)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVim/connect.py", line 269, in Connect
    keyFile, certFile, thumbprint, sslContext, b64token, connectionPoolTimeout)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVim/connect.py", line 444, in __LoginBySSPI
    x = content.sessionManager.LoginBySSPI(b64token)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Users/gaudalvi/.local/share/virtualenvs/ccp-api-Zlccl3x_/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

**Comment by sownthararaj** [comment]
Did you find the fix for this?

**Comment by MdKalim** [comment]
Any method you found?
