### ISSUE TITLE
test connection

### ISSUE THREAD

**Issue by houcinedz** [vmware/pyvmomi#779]
from pyvim.connect import SmartConnectNoSSL, Disconnect

import atexit

si = SmartConnectNoSSL(host='******', user='*******', pwd='******', port=443)
atexit.register(Disconnect, si)
content = si.RetrieveContent()
print content

------------------------------- i get this problem ------------ python 2.7-----------------

Traceback (most recent call last):
  File "C:/Users/power/PycharmProjects/vSphere/test.py", line 5, in <module>
    si = SmartConnectNoSSL(host='*******', user=*******', pwd='*******', port=443)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 888, in SmartConnectNoSSL
    mechanism=mechanism)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 856, in SmartConnect
    mechanism=mechanism)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 266, in Connect
    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)
  File "C:\Python27\lib\site-packages\pyvim\connect.py", line 390, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "C:\Python27\lib\site-packages\pyVmomi\SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Cannot complete login due to an incorrect user name or password.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by kumahesh** [comment]
Hi @houcinedz , 
I believe you might have removed values for the sensitive parameters from the logs before posting here. It is okay.
but pass appropriate values for the host, user and pwd while calling 'SmartConnectNoSSL' method.
Refer the getallvms samples [here](https://github.com/vmware/pyvmomi-community-samples/blob/17ddffaab6a9bd1d262038f954f6bf41e4b4dfcb/samples/getallvms.py#L71)

if you do not pass parameters, It will take default value as follows as
host = localhost
user= root
pwd=''
