### ISSUE TITLE
Issue in pyVim.connect , says __init__() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by 01pooja** [vmware/pyvmomi#791]
si = connect.SmartConnectNoSSL(
            host=vc_host,
            port=int(port),
            user=user,
            pwd=_base64_str(password),
        )

The error is at the above statement, what else need to be passed to this ?

Thank you

**Comment by pgbidkar** [comment]
Hi @01pooja , Please can you share your script. 

Thanks

**Comment by 01pooja** [comment]
Hey @pgbidkar 

Please find the below snippet:

`sys.path.insert(0,"./mypython/lib/python2.7/site-packages")
import pyVmomi
from pyVim import connect

def check_esx_connection(hostinfo, vc_host):
    port= 444
    user = "bb"
    password = "aa"
    si = None
    try:

        logging.info("Vchost:: %s" %(vc_host))
        si = connect.SmartConnectNoSSL(
            host=vc_host,
            port=int(port),
            user=user,
            pwd=_base64_str(password),
        )
        logging.info("si:::::::: %s" %(si))
        content = si.RetrieveContent()
        logging.info("conetnet:: %s" %(content))
        vms = get_vim_objects(content, pyVmomi.vim.VirtualMachine)
        for vm in vms:
            if not hostinfo['hostname'] in vm.name:
                return False
        return True
    except Exception,ex:
        logging.critical("Exception while connecting to VC host %s" %(ex))

`

**Comment by pgbidkar** [comment]
Hi @01pooja , Please can you try this works in your env?
Without this _base64_str(password).

```
import pyVmomi
from pyVim import connect

def check_connection(hostname):
    port= 443
    si = None
    si = connect.SmartConnectNoSSL(
        host=hostname,
        port=int(port),
        user='user',
        pwd='pass'
    )
    print (si)
    print (si.content)

check_connection('VCIP')
```

**Comment by 01pooja** [comment]
It works in my environment without  _base64_str(password).

**Comment by 01pooja** [comment]
The above snippet says:

(mypython) bash-4.2$ python test_vc1.py
Traceback (most recent call last):
  File "test_vc1.py", line 16, in <module>
    check_connection('VCIP')
  File "test_vc1.py", line 11, in check_connection
    pwd='pass'
  File "/data/work/pog-stage-apps1/mypython/lib/python2.7/site-packages/pyVim/connect.py", line 888, in SmartConnectNoSSL
    mechanism=mechanism)
  File "/data/work/pog-stage-apps1/mypython/lib/python2.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/data/work/pog-stage-apps1/mypython/lib/python2.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/data/work/pog-stage-apps1/mypython/lib/python2.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/data/work/pog-stage-apps1/mypython/lib/python2.7/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1251, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by 01pooja** [comment]
Issue is with _base64_str(password).  base64 module was not imported. Hence closing the issue. Thank you @pgbidkar
