### ISSUE TITLE
AttributeError: 'vim.Folder' object has no attribute 'host'

### ISSUE THREAD

**Issue by klainn** [vmware/pyvmomi#800]
Running the sample code getvmsbycluster.py and I receive this error.

`Traceback (most recent call last):
  File "C:/Users/<me>//PycharmProjects/vmware_clusters/getvmsbycluster.py", line 158, in <module>
    main()
  File "C:/Users/<me>/PycharmProjects/vmware_clusters/getvmsbycluster.py", line 136, in main
    hosts = cluster.host
AttributeError: 'vim.Folder' object has no attribute 'host'`

I can't seem to track it down where this is coming from.

The lines referenced in the error are:

line 136:
` hosts = cluster.host`

line 158:
`main()`

I can't seem to pick out what in vcenter would be causing this either. All the clusters that it seems to choke on seem configured normally.

**Comment by klainn** [comment]
I've found the reason for this to be inside the datacenter, there are folders filled with clusters instead of just clusters as the code is expecting. Not 100% sure how to proceed just yet.

**Comment by pgbidkar** [comment]
Hi @klainn , It looks like setup issue. Please can you check you have hosts part of Cluster? 
I couldn't reproduce this issue

Thanks

**Comment by klainn** [comment]
I'm not sure what you mean by setup issue, how vcenter is setup or how i've setup the python environment.

We get 10 errors when we try to run the code, we have 1 data center in vsphere with 10 clusters but they are all in folders. The structure is as such:

- Datacenter
-      Folder1
-           cluster
-           cluster
-      Folder2
-           cluster
-           cluster
-           cluster
-           cluster
-      Folder3
-           cluster
-      Folder4
-           cluster
-      Folder5
-           cluster
-      Folder6
-           cluster
-      Folder7
-           cluster
-      Folder8
-           cluster
-      Folder9
-           cluster
-      Folder10
-           cluster
- 

Some folders have more than one cluster. One folder has the following setup
Folder
     Folder
          Cluster

All cluster have at least 1 running host and vms running inside them.  There are no clusters inside folders that do not have hosts.

**Comment by RajkumarShivage** [comment]
AttributeError: 'vim.Folder' object has no attribute 'hostFolder' 
facing similar issue.

**Comment by sysThematic** [comment]
You can discard Folder Object types by using control below:
if cluster._wsdlName != "Folder":
