### ISSUE TITLE
Tests fail with python2 and version 6.7.3

### ISSUE THREAD

**Issue by rapgro** [vmware/pyvmomi#837]
Several tests don't work any more with version 6.7.3, e.g.:

```
BUILDSTDERR: ERROR: test_ssl_tunnel (tests.test_connect.ConnectionTests)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 98, in __call__
BUILDSTDERR:     return function(*args, **kwargs)
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/tests/test_connect.py", line 96, in test_ssl_tunnel
BUILDSTDERR:     connect.SoapStubAdapter('sdkTunnel', 8089, httpProxyHost='vcsa').GetConnection()
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1428, in GetConnection
BUILDSTDERR:     result = self.scheme(self.host, **self.schemeArgs)
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1123, in __call__
BUILDSTDERR:     conn.set_tunnel(self.proxyPath)
BUILDSTDERR: AttributeError: 'VCRHTTPSConnection/builddir/build/BUILD/pyvmomi-6.' object has no attribute 'set_tunnel'
```

For now, I decided to stop support for the python2 subpackage in EPEL7 (addons repository for RHEL7 and CentOS7) in favour of python3 with its own subpackage.

**Comment by rapgro** [comment]
```
BUILDSTDERR: ERROR: test_http_proxy (tests.test_connect.ConnectionTests)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 98, in __call__
BUILDSTDERR:     return function(*args, **kwargs)
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/tests/test_connect.py", line 127, in test_http_proxy
BUILDSTDERR:     httpProxyPort=8080).GetConnection()
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1428, in GetConnection
BUILDSTDERR:     result = self.scheme(self.host, **self.schemeArgs)
BUILDSTDERR:   File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1123, in __call__
BUILDSTDERR:     conn.set_tunnel(self.proxyPath)
BUILDSTDERR: AttributeError: 'VCRHTTPSConnection/builddir/build/BUILD/pyvmomi-6.' object has no attribute 'set_tunnel'
```

**Comment by pgbidkar** [comment]
Hi @rapgro , please can you share python 2 version? Try updating it to next version. (2.7.16)

Thanks

**Comment by rapgro** [comment]
Python 2.7.5
The package version is 2.7.5-86.el7, so there seems to be heavy patching with -86 as the release tag or patches count. We can't update Python to a new major version in EPEL7 because it's a package in RHEL7 maintained by Red Hat.
But I'm going to retest with RHEL8 plus EPEL8 and come back to report of any results.

**Comment by rapgro** [comment]
EPEL8...
```
Start: build phase for python-pyvmomi-6.7.3-2.el8.src.rpm
Start: build setup for python-pyvmomi-6.7.3-2.el8.src.rpm
ERROR: Exception(/var/tmp/koji/tasks/2370/37702370/local/work/cli-build/1568721803.565503.nkWPXduH/python-pyvmomi-6.7.3-2.el8.src.rpm) Config(epel8-build-17532033-1264455) 0 minutes 4 seconds
INFO: Results and/or logs in: /var/lib/mock/epel8-build-17532033-1264455/result
ERROR: Command failed: 
 # /usr/bin/dnf builddep --installroot /var/lib/mock/epel8-build-17532033-1264455/root/ --setopt=install_weak_deps=0 --disableplugin=local --disableplugin=spacewalk /var/lib/mock/epel8-build-17532033-1264455/root//builddir/build/SRPMS/python-pyvmomi-6.7.3-2.el8.src.rpm --setopt=tsflags=nocontexts
Last metadata expiration check: 0:00:01 ago on Tue Sep 17 12:03:33 2019.
No matching package to install: 'python-fixtures'
No matching package to install: 'python-testtools'
No matching package to install: 'python-tox'
No matching package to install: 'python-vcrpy'
Not all dependencies satisfied
Error: Some packages could not be found.
```

This means no good chance for any python2 builds with RHEL. Still in assumption we can skip over to support python3 only. Also there's EOL announced officially for any python2.
https://pythonclock.org/

**Comment by kumahesh** [comment]
Any update on the issue?
Can we close the issue?
