### ISSUE TITLE
tests.test_connect.ConnectionTests fail on RHEL7

### ISSUE THREAD

**Issue by rathann** [vmware/pyvmomi#865]
When running `6.7.3` test suite on RHEL7 (`python 2.7.5`), the following tests fail:
```
======================================================================
ERROR: test_http_proxy (tests.test_connect.ConnectionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 130, in _handle_function
    return self.__handle_function(cassette, function, args, kwargs)
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 126, in __handle_function
    return function(*args, **kwargs)
  File "/builddir/build/BUILD/pyvmomi-6.7.3/tests/test_connect.py", line 127, in test_http_proxy
    httpProxyPort=8080).GetConnection()
  File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1428, in GetConnection
    result = self.scheme(self.host, **self.schemeArgs)
  File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1123, in __call__
    conn.set_tunnel(self.proxyPath)
AttributeError: 'VCRHTTPSConnection/builddir/build/BUILD/pyvmomi-6.' object has no attribute 'set_tunnel'

======================================================================
ERROR: test_ssl_tunnel (tests.test_connect.ConnectionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 130, in _handle_function
    return self.__handle_function(cassette, function, args, kwargs)
  File "/usr/lib/python2.7/site-packages/vcr/cassette.py", line 126, in __handle_function
    return function(*args, **kwargs)
  File "/builddir/build/BUILD/pyvmomi-6.7.3/tests/test_connect.py", line 96, in test_ssl_tunnel
    connect.SoapStubAdapter('sdkTunnel', 8089, httpProxyHost='vcsa').GetConnection()
  File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1428, in GetConnection
    result = self.scheme(self.host, **self.schemeArgs)
  File "/builddir/build/BUILD/pyvmomi-6.7.3/pyVmomi/SoapAdapter.py", line 1123, in __call__
    conn.set_tunnel(self.proxyPath)
AttributeError: 'VCRHTTPSConnection/builddir/build/BUILD/pyvmomi-6.' object has no attribute 'set_tunnel'

----------------------------------------------------------------------
Ran 31 tests in 5.029s

FAILED (errors=2)
```

I'm not sure why, because the set_tunnel method seems to be there:
```
$ python2
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from six.moves import http_client
>>> conn=http_client.HTTPSConnection("fedoraproject.org:443")
>>> conn.set_tunnel("localhost")
>>> 
```
My guess is that's an issue with the testing environment/tools.

**Comment by rapgro** [comment]
Be aware the tests fail for python2 but not for python3. Already discussed in #837 .
