### ISSUE TITLE
Esxi 7 support

### ISSUE THREAD

**Issue by darox** [vmware/pyvmomi#916]
Starting from Esxi 7 on I can't connect to the esxi node anymore:

Traceback (most recent call last):
  File "esxi-1-list-vms.py", line 35, in <module>
    vconnect()
  File "esxi-1-list-vms.py", line 15, in vconnect
    sslContext=s)
  File "/home/dario/.local/lib/python3.7/site-packages/pyVim/connect.py", line 847, in SmartConnect
    sslContext)
  File "/home/dario/.local/lib/python3.7/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
    httpProxyPort)
  File "/home/dario/.local/lib/python3.7/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
    httpProxyHost, httpProxyPort)
  File "/home/dario/.local/lib/python3.7/site-packages/pyVim/connect.py", line 608, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

Is Esxi 7 supported?

**Comment by darox** [comment]
Setting 
`s = ssl.SSLContext(ssl.PROTOCOL_TLSv1)`

to

`s = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`

fixes it.
