### ISSUE TITLE
InvalidGuestLogin on rhel 7 with the good ldap account

### ISSUE THREAD

**Issue by aboubiz** [vmware/pyvmomi#928]
Hi,
When it uses pyvmomi for execute a command on a vm rhel 7.8 with  ldap account and pam sssd module, the pyvmomi module return vim.fault.InvalidGuestLogin
Whereas it can to connect on the vm console with the same account.
For information, this performs with a sles 12 sp5 vm and with the system configuration.

./VirtualMachine.py --hostname rappdepotrh07lab1
Traceback (most recent call last):
  File "./VirtualMachine.py", line 490, in <module>
    vm.updateOs()
  File "./VirtualMachine.py", line 274, in updateOs
    self.executeCommand(username, password, "/usr/bin/sudo" , "yum -y update --setopt tsflags=test", True)
  File "./VirtualMachine.py", line 425, in executeCommand
    res = pm.StartProgramInGuest(self.vcvm, creds, ps)
  File "/home/vincent.cieslak/Documents/pro/projets/updateos/virtualenv/vcenter/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/vincent.cieslak/Documentalors ques/pro/projets/updateos/virtualenv/vcenter/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/vincent.cieslak/Documents/pro/projets/updateos/virtualenv/vcenter/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
Regards

**Comment by tony23** [comment]
I know this issue is pretty old but I'm running into the same thing.

Any chance that password has an ampersand? I discovered that it doesn't handle ampersands in the password.
