### ISSUE TITLE
TypeError: Object of type 'vim.vm.Capability' is not JSON serializable

### ISSUE THREAD

**Issue by Pigi-102** [vmware/pyvmomi#981]
### Describe the bug

I was trying an inventory with the followong yaml:
```
---
plugin: vmware_vm_inventory
strict: False
hostname: vc.contoso.com
username: contoso\ansible
password: VeryHardPassword
validate_certs: False
hostnames:
- 'config.name'
properties:
- name
- network
- overallStatus
- value
- capability
- config
- guest
- runtime
- summary
with_tags: true
keyed_groups:
- key: tags
  prefix: "vm_tag_"
  separator: ""
- key: config.guestId
  prefix: ''
  separator: ''
- key: summary.runtime.powerState
  prefix: ''
  separator: ''
```
and get the following:
```
ansible-inventory 2.9.27
  config file = /root/vmware/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 10 2021, 06:50:23) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3.0.2)]
Using /root/vmware/ansible.cfg as config file
setting up inventory plugins
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{' '}" in group name (OS Windows)
Not replacing invalid character(s) "{' '}" in group name (Silver Tier)
Not replacing invalid character(s) "{'.'}" in group name (com.vmware.vr.HasVrDisks)
Not replacing invalid character(s) "{' '}" in group name (Gold Tier)
Not replacing invalid character(s) "{' '}" in group name (OS Linux)
Parsed /root/vmware/basic1.vmware.yaml inventory source with vmware_vm_inventory plugin
ERROR! Unexpected Exception, this is probably a bug: Object of type 'vim.vm.Capability' is not JSON serializable
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-inventory", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.6/site-packages/ansible/cli/inventory.py", line 149, in run
    results = self.dump(results)
  File "/usr/lib/python3.6/site-packages/ansible/cli/inventory.py", line 183, in dump
    results = json.dumps(stuff, cls=AnsibleJSONEncoder, sort_keys=True, indent=4, preprocess_unsafe=True)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/site-packages/ansible/module_utils/common/json.py", line 63, in default
    value = super(AnsibleJSONEncoder, self).default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'vim.vm.Capability' is not JSON serializable
```

if instead i use :
```
---
plugin: vmware_vm_inventory
strict: False
hostname: vc.contoso.com
username: contoso\ansible
password: VeryHardPassword
validate_certs: False
with_tags: true

```
I get the inventory.

### Reproduction steps

```bash
1. create a file basic1.vmware.yaml with the yaml as descripted previously
2. run ansible-inventory -vvvv --list -i basic1.vmware.yaml
```

### Expected behavior

I do expect a list of hosts.

**Comment by Pigi-102** [comment]
It looks that if I use the following yaml:
```
properties:
- 'config.name'
- 'config.guestId'
- 'guest.ipAddress'
- 'summary.runtime.powerState'
- 'guest.toolsStatus'
- 'guest.toolsRunningStatus'
- 'guest.guestFamily'
- 'guest.hostName'
keyed_groups:
  - key: guest.toolsStatus
    separator: ''
  - key: guest.toolsRunningStatus
    separator: ''
  - key: guest.guestFamily
    separator: ''
compose:
  ansible_host: 'guest.hostName'

```

I don't get the error.
I'm going to close this but leave for future.
